@generated
Call dependencies
{
  "access_path.SpecialDict.__getitem__ (method)": [ "dict.get (method)" ],
  "access_path.indexes_and_attributes (fun)": [
    "_test_sink (fun)", "_test_source (fun)",
    "access_path.SpecialDict.__getitem__ (method)",
    "access_path.SpecialDict.__init__ (method)", "object.__new__ (method)"
  ],
  "access_path.indexes_are_attributes_for___dict__ (fun)": [
    "_test_sink (fun)", "_test_source (fun)", "object.__init__ (method)",
    "object.__new__ (method)"
  ],
  "access_path.indexes_are_strings (fun)": [
    "_test_sink (fun)", "_test_source (fun)", "dict.__getitem__ (method)",
    "dict.__setitem__ (method)"
  ],
  "access_path.issue_positional_and_variadic (fun)": [
    "_test_source (fun)", "access_path.positional_and_variadic1 (fun)",
    "access_path.positional_and_variadic2 (fun)"
  ],
  "access_path.positional_and_variadic1 (fun)": [ "_test_sink (fun)" ],
  "access_path.positional_and_variadic2 (fun)": [ "_test_sink (fun)" ]
}