@generated
Call dependencies
{
  "add_feature_to_argument.add_feature_to_argument_accumulates_features (fun)": [
    "add_feature_to_argument.add_feature_to_first (fun)",
    "add_feature_to_argument.tito_with_feature (fun)"
  ],
  "add_feature_to_argument.adds_and_taints (fun)": [
    "add_feature_to_argument.add_feature_to_first (fun)",
    "pysa._test_source (fun)"
  ],
  "add_feature_to_argument.dict_test_add_via_value_of_second (fun)": [
    "add_feature_to_argument.add_via_value_of (fun)",
    "pysa._test_source (fun)"
  ],
  "add_feature_to_argument.propagate_add_feature (fun)": [
    "add_feature_to_argument.add_feature_to_first (fun)"
  ],
  "add_feature_to_argument.propagate_multiple_add_feature (fun)": [
    "add_feature_to_argument.add_feature_to_second (fun)"
  ],
  "add_feature_to_argument.source_add_feature_to_argument_accumulates_features (fun)": [
    "add_feature_to_argument.add_feature_to_argument_accumulates_features (fun)",
    "pysa._test_source (fun)"
  ],
  "add_feature_to_argument.test_add_feature_in_comprehension (fun)": [
    "add_feature_to_argument.add_feature_to_first (fun)",
    "builtins.list.__getitem__ (method)", "builtins.list.__iter__ (method)",
    "pysa._test_sink (fun)", "pysa._test_source (fun)",
    "typing.Iterator.__next__ (method)"
  ],
  "add_feature_to_argument.test_add_feature_to_sink (fun)": [
    "add_feature_to_argument.add_feature_to_first (fun)",
    "pysa._test_sink (fun)"
  ],
  "add_feature_to_argument.test_add_feature_to_sink_in_comprehension (fun)": [
    "add_feature_to_argument.add_feature_to_first (fun)",
    "builtins.list.__iter__ (method)", "pysa._test_sink (fun)",
    "typing.Iterator.__next__ (method)"
  ],
  "add_feature_to_argument.test_add_multiple_feature (fun)": [
    "add_feature_to_argument.propagate_multiple_add_feature (fun)",
    "pysa._test_sink (fun)"
  ],
  "add_feature_to_argument.test_add_via_value_of_second (fun)": [
    "add_feature_to_argument.add_via_value_of (fun)",
    "pysa._test_source (fun)"
  ]
}