@generated
Call dependencies
{
  "add_breadcrumb_to_state.add_breadcrumb_to_state_wrapper (fun)": [
    "add_breadcrumb_to_state.add_breadcrumb_to_state (fun)"
  ],
  "add_breadcrumb_to_state.test_add_breadcrumb_context_manager (fun)": [
    "_test_sink (fun)", "_test_source (fun)",
    "add_breadcrumb_to_state.BreadcrumbOnEnter.__enter__ (method)",
    "add_breadcrumb_to_state.BreadcrumbOnEnter.__init__ (method)",
    "object.__new__ (method)"
  ],
  "add_breadcrumb_to_state.test_if_issue (fun)": [
    "_test_sink (fun)", "_test_source (fun)",
    "add_breadcrumb_to_state.add_breadcrumb_to_state (fun)"
  ],
  "add_breadcrumb_to_state.test_if_sink_outside_condition (fun)": [
    "_test_sink (fun)",
    "add_breadcrumb_to_state.add_breadcrumb_to_state (fun)"
  ],
  "add_breadcrumb_to_state.test_if_sink_within_condition (fun)": [
    "_test_sink (fun)",
    "add_breadcrumb_to_state.add_breadcrumb_to_state (fun)"
  ],
  "add_breadcrumb_to_state.test_if_source_outside_condition (fun)": [
    "_test_source (fun)",
    "add_breadcrumb_to_state.add_breadcrumb_to_state (fun)"
  ],
  "add_breadcrumb_to_state.test_if_source_within_condition (fun)": [
    "_test_source (fun)",
    "add_breadcrumb_to_state.add_breadcrumb_to_state (fun)"
  ],
  "add_breadcrumb_to_state.test_wrapper (fun)": [
    "_test_sink (fun)", "_test_source (fun)",
    "add_breadcrumb_to_state.add_breadcrumb_to_state_wrapper (fun)"
  ]
}