@generated
Call dependencies
{
  "any_index.post_0 (fun)": [
    "builtins.dict.__getitem__ (method)",
    "builtins.dict.__setitem__ (method)", "pysa._test_source (fun)"
  ],
  "any_index.post_1 (fun)": [
    "builtins.dict.__getitem__ (method)",
    "builtins.dict.__setitem__ (method)", "pysa._test_source (fun)"
  ],
  "any_index.post_2 (fun)": [
    "_random.Random.random (method)", "builtins.dict.__getitem__ (method)",
    "builtins.dict.__setitem__ (method)", "builtins.float.__gt__ (method)",
    "pysa._test_source (fun)"
  ],
  "any_index.post_3 (fun)": [
    "_random.Random.random (method)", "builtins.dict.__getitem__ (method)",
    "builtins.dict.__setitem__ (method)", "builtins.float.__gt__ (method)",
    "pysa._test_source (fun)"
  ],
  "any_index.pre_0 (fun)": [
    "builtins.dict.__getitem__ (method)",
    "builtins.dict.__setitem__ (method)", "pysa._test_sink (fun)"
  ],
  "any_index.pre_1 (fun)": [
    "builtins.dict.__getitem__ (method)",
    "builtins.dict.__setitem__ (method)", "pysa._test_sink (fun)"
  ],
  "any_index.pre_2 (fun)": [
    "_random.Random.random (method)", "builtins.dict.__getitem__ (method)",
    "builtins.dict.__setitem__ (method)", "builtins.float.__gt__ (method)",
    "pysa._test_sink (fun)"
  ],
  "any_index.pre_3 (fun)": [
    "_random.Random.random (method)", "builtins.dict.__getitem__ (method)",
    "builtins.dict.__setitem__ (method)", "builtins.float.__gt__ (method)",
    "pysa._test_sink (fun)"
  ]
}