@generated
Call dependencies
{
  "any_index.post_0 (fun)": [
    "dict.__getitem__ (method)", "dict.__setitem__ (method)",
    "pysa._test_source (fun)"
  ],
  "any_index.post_1 (fun)": [
    "dict.__getitem__ (method)", "dict.__setitem__ (method)",
    "pysa._test_source (fun)"
  ],
  "any_index.post_2 (fun)": [
    "dict.__getitem__ (method)", "dict.__setitem__ (method)",
    "int.__gt__ (method)", "int.__le__ (method)", "pysa._test_source (fun)"
  ],
  "any_index.post_3 (fun)": [
    "dict.__getitem__ (method)", "dict.__setitem__ (method)",
    "int.__gt__ (method)", "int.__le__ (method)", "pysa._test_source (fun)"
  ],
  "any_index.pre_0 (fun)": [
    "dict.__getitem__ (method)", "dict.__setitem__ (method)",
    "pysa._test_sink (fun)"
  ],
  "any_index.pre_1 (fun)": [
    "dict.__getitem__ (method)", "dict.__setitem__ (method)",
    "pysa._test_sink (fun)"
  ],
  "any_index.pre_2 (fun)": [
    "dict.__getitem__ (method)", "dict.__setitem__ (method)",
    "int.__gt__ (method)", "int.__le__ (method)", "pysa._test_sink (fun)"
  ],
  "any_index.pre_3 (fun)": [
    "dict.__getitem__ (method)", "dict.__setitem__ (method)",
    "int.__gt__ (method)", "int.__le__ (method)", "pysa._test_sink (fun)"
  ]
}