@generated
Call dependencies
{
  "applies_to_index.issue_only_with_a_key (fun)": [
    "applies_to_index.only_applies_to_a_key (fun)",
    "builtins.dict.__getitem__ (method)", "pysa._test_sink (fun)"
  ],
  "applies_to_index.issue_only_with_first (fun)": [
    "applies_to_index.only_applies_to_first (fun)", "pysa._test_sink (fun)"
  ],
  "applies_to_index.issue_only_with_nested_first (fun)": [
    "applies_to_index.only_applies_to_nested (fun)", "pysa._test_sink (fun)"
  ],
  "applies_to_index.issue_only_with_second (fun)": [
    "applies_to_index.only_applies_to_second (fun)", "pysa._test_sink (fun)"
  ],
  "applies_to_index.issue_with_member (fun)": [
    "applies_to_index.only_applies_to_a_member (fun)",
    "pysa._test_sink (fun)"
  ]
}