@generated
Call dependencies
{
  "attributes.$toplevel (fun)": [ "dataclasses.dataclass (fun)" ],
  "attributes.NoListInference.append (method)": [
    "builtins.list.append (method)"
  ],
  "attributes.NoListInference.sink (method)": [ "pysa._test_sink (fun)" ],
  "attributes.Request.$class_toplevel (fun)": [
    "builtins.object.__init__ (method)", "builtins.object.__new__ (method)"
  ],
  "attributes.test_attribute (fun)": [ "attributes.Token.token (object)" ],
  "attributes.test_attribute_union_sink (fun)": [
    "attributes.Sink.token (object)", "builtins.isinstance (fun)",
    "pysa._test_source (fun)"
  ],
  "attributes.test_attribute_union_source (fun)": [
    "attributes.Token.token (object)", "builtins.isinstance (fun)",
    "pysa._test_sink (fun)"
  ],
  "attributes.test_attribute_via_dunder_dict (fun)": [
    "attributes.UseViaDict.__init__ (method)",
    "builtins.dict.__getitem__ (method)", "builtins.object.__new__ (method)",
    "pysa._test_sink (fun)", "pysa._test_source (fun)"
  ],
  "attributes.test_getattr_backwards (fun)": [
    "attributes.Token.token (object)", "builtins.getattr (fun)",
    "pysa._test_sink (fun)"
  ],
  "attributes.test_getattr_backwards_default (fun)": [
    "attributes.Token.token (object)", "builtins.getattr (fun)",
    "pysa._test_sink (fun)"
  ],
  "attributes.test_getattr_default (fun)": [
    "builtins.getattr (fun)", "pysa._test_source (fun)"
  ],
  "attributes.test_getattr_forward (fun)": [
    "attributes.Token.token (object)", "builtins.getattr (fun)"
  ],
  "attributes.test_issue_with_text_key_of_dictionary (fun)": [
    "attributes.C.dictionary (object)", "builtins.dict.__getitem__ (method)",
    "pysa._test_sink (fun)"
  ],
  "attributes.test_issue_with_tito_copy_dict (fun)": [
    "attributes.tito_copy_dict (fun)", "pysa._test_sink (fun)",
    "pysa._test_source (fun)"
  ],
  "attributes.test_issue_with_tito_copy_multiple_possible_dictlike_objects (fun)": [
    "attributes.RegularForm.__init__ (method)",
    "attributes.tito_copy_multiple_possible_dictlike_objects (fun)",
    "builtins.object.__new__ (method)", "pysa._test_sink (fun)",
    "pysa._test_source (fun)", "typing.Mapping.__getitem__ (method)"
  ],
  "attributes.test_issue_with_update_to_self_attribute (fun)": [
    "attributes.D.buffer (object)", "builtins.list.append (method)",
    "pysa._test_source (fun)"
  ],
  "attributes.test_no_issue_sanitize (fun)": [
    "builtins.object.__init__ (method)", "builtins.object.__new__ (method)",
    "pysa._test_sink (fun)", "pysa._test_source (fun)"
  ],
  "attributes.test_no_issue_sanitize_via_call (fun)": [
    "attributes.sanitize_attribute (fun)",
    "builtins.object.__init__ (method)", "builtins.object.__new__ (method)",
    "pysa._test_sink (fun)", "pysa._test_source (fun)"
  ],
  "attributes.test_no_issue_with_other_key_of_dictionary (fun)": [
    "attributes.C.dictionary (object)", "builtins.dict.__getitem__ (method)",
    "pysa._test_sink (fun)"
  ],
  "attributes.test_no_list_inference (fun)": [
    "attributes.NoListInference.__init__ (method)",
    "attributes.NoListInference.append (method)",
    "attributes.NoListInference.sink (method)",
    "builtins.object.__new__ (method)", "pysa._test_source (fun)"
  ],
  "attributes.test_via_non_optional (fun)": [
    "attributes.Token.token (object)"
  ],
  "attributes.test_via_optional (fun)": [ "attributes.Token.token (object)" ],
  "attributes.tito_copy_multiple_possible_dictlike_objects (fun)": [
    "attributes.PartiallyZonedDict.copy (method)",
    "attributes.ZonedForm.data (method)", "builtins.dict.copy (method)"
  ]
}