@generated
Call dependencies
{
  "binary_operators.Add.__add__ (method)": [ "pysa._test_sink (fun)" ],
  "binary_operators.test1 (fun)": [
    "binary_operators.Add.__add__ (method)",
    "builtins.object.__init__ (method)", "builtins.object.__new__ (method)",
    "pysa._test_source (fun)"
  ],
  "binary_operators.test2 (fun)": [
    "binary_operators.Add.__add__ (method)",
    "builtins.object.__init__ (method)", "builtins.object.__new__ (method)",
    "pysa._test_source (fun)"
  ]
}