@generated
Call dependencies
{
  "breadcrumbs.bool_parameter (fun)": [ "pysa._test_sink (fun)" ],
  "breadcrumbs.bool_source (fun)": [ "pysa._test_source (fun)" ],
  "breadcrumbs.float_parameter (fun)": [ "pysa._test_sink (fun)" ],
  "breadcrumbs.float_source (fun)": [ "pysa._test_source (fun)" ],
  "breadcrumbs.int_parameter (fun)": [ "pysa._test_sink (fun)" ],
  "breadcrumbs.int_source (fun)": [ "pysa._test_source (fun)" ],
  "breadcrumbs.scalar_attribute_backward (fun)": [
    "_random.Random.random (method)", "builtins.float.__gt__ (method)",
    "builtins.list.__iter__ (method)", "builtins.object.__init__ (method)",
    "builtins.object.__repr__ (method)", "builtins.str.__new__ (method)",
    "builtins.str.join (method)", "pysa._test_sink (fun)",
    "typing.Iterator.__next__ (method)"
  ],
  "breadcrumbs.scalar_attribute_forward (fun)": [
    "_random.Random.random (method)", "breadcrumbs.tpm_request (fun)",
    "builtins.float.__gt__ (method)", "builtins.list.__iter__ (method)",
    "builtins.object.__init__ (method)", "builtins.object.__repr__ (method)",
    "builtins.str.__new__ (method)", "builtins.str.join (method)",
    "typing.Iterator.__next__ (method)"
  ]
}