@generated
Call dependencies
{
  "breadcrumbs.bool_parameter (fun)": [ "pysa._test_sink (fun)" ],
  "breadcrumbs.bool_source (fun)": [ "pysa._test_source (fun)" ],
  "breadcrumbs.float_parameter (fun)": [ "pysa._test_sink (fun)" ],
  "breadcrumbs.float_source (fun)": [ "pysa._test_source (fun)" ],
  "breadcrumbs.int_parameter (fun)": [ "pysa._test_sink (fun)" ],
  "breadcrumbs.int_source (fun)": [ "pysa._test_source (fun)" ],
  "breadcrumbs.scalar_attribute_forward (fun)": [
    "breadcrumbs.tpm_request (fun)"
  ]
}