@generated
Call dependencies
callables.AbstractEventProcessor::__init__ (method) -> []
callables.AbstractEventProcessor::async_call_tainted (method) -> []
callables.AbstractEventProcessor::async_run (method) -> []
callables.ConcreteEventProcessor::async_call_tainted (method) -> [_test_sink (fun)]
callables.ConcreteEventProcessor::async_run (method) -> [_test_sink (fun)]
callables.ProcessorInfo::__init__ (method) -> []
callables.async_execute_event_processor (fun) -> [_test_source (fun) callables.AbstractEventProcessor::__init__ (method) callables.AbstractEventProcessor::async_call_tainted (override) callables.AbstractEventProcessor::async_run (override) callables.get_event_processors (fun) list::__iter__ (method) object::__new__ (method) typing.Iterator::__next__ (method)]
