@generated
Call dependencies
{
  "call_graph.CallableKindConfusion.foo@decorated (method)": [
    "call_graph.no_op_decorator (fun)[formal(f, position=0)=call_graph.CallableKindConfusion.foo (fun)]",
    "call_graph.no_op_decorator (fun)[formal(f, position=0)=call_graph.CallableKindConfusion.foo (method)]",
    "call_graph.no_op_decorator_factory (fun)",
    "call_graph.no_op_decorator_factory.inner (fun)[formal(original, position=0)=call_graph.CallableKindConfusion.foo (method)]"
  ],
  "call_graph.IsSource.method (method)": [ "_test_source (fun)" ],
  "call_graph.is_dict (fun)": [ "isinstance (fun)" ],
  "call_graph.test_chained_assign (fun)": [
    "_test_sink (fun)", "call_graph.NotSource.__init__ (method)",
    "call_graph.NotSource.method (method)", "object.__new__ (method)"
  ],
  "call_graph.test_chained_assign_subscript (fun)": [
    "call_graph.is_dict (fun)", "dict.__getitem__ (method)"
  ],
  "call_graph.test_default_parameters (fun)": [
    "_test_sink (fun)", "_test_source (fun)"
  ],
  "call_graph.test_localized_target (fun)": [
    "call_graph.test_localized_target.f (fun)", "int.__ge__ (method)",
    "int.__lt__ (method)"
  ]
}