@generated
Call dependencies
{
  "class_interval.A0.m1 (method)": [ "class_interval.A0.m2 (override)" ],
  "class_interval.A1.m1 (method)": [ "class_interval.A1.m2 (override)" ],
  "class_interval.A10.object_target (method)": [
    "class_interval.A10.f (object)", "object.__init__ (method)",
    "object.__new__ (method)"
  ],
  "class_interval.A13.f (method)": [ "class_interval.A13.g (override)" ],
  "class_interval.A14.m1 (method)": [ "class_interval.A14.m2 (override)" ],
  "class_interval.A15.m1 (method)": [ "class_interval.A15.m2 (override)" ],
  "class_interval.A16.m1 (method)": [ "class_interval.A16.m2 (override)" ],
  "class_interval.A17.m0 (method)": [ "class_interval.A17.m1 (override)" ],
  "class_interval.A17.m2 (method)": [ "class_interval.D17.m1 (method)" ],
  "class_interval.A19.m0 (method)": [ "class_interval.A19.m1 (method)" ],
  "class_interval.A19.m1 (method)": [ "_test_sink (fun)" ],
  "class_interval.A19.m2 (method)": [ "class_interval.A19.m3 (method)" ],
  "class_interval.A19.m3 (method)": [ "_test_sink (fun)" ],
  "class_interval.A2.m1 (method)": [ "class_interval.A2.m2 (override)" ],
  "class_interval.A21.m0 (method)": [ "class_interval.A21.m1 (override)" ],
  "class_interval.A22.m0 (method)": [ "class_interval.A22.m1 (override)" ],
  "class_interval.A23.m0 (method)": [ "class_interval.A23.m1 (override)" ],
  "class_interval.A24.m0 (method)": [
    "class_interval.A24.m1 (override)", "class_interval.A24.tito (method)"
  ],
  "class_interval.A3.m1 (method)": [ "class_interval.A3.m2 (override)" ],
  "class_interval.A4.m2 (method)": [ "class_interval.A4.m3 (override)" ],
  "class_interval.A5.m1 (method)": [ "class_interval.A5.m2 (override)" ],
  "class_interval.A6.m1 (method)": [ "class_interval.A6.m0 (override)" ],
  "class_interval.A7.f (method)": [ "class_interval.B7.foo (method)" ],
  "class_interval.A8.bar (method)": [
    "class_interval.A8.baz (method)", "class_interval.B8.foo (method)",
    "class_interval.C8.foo (method)", "object.__init__ (method)",
    "object.__new__ (method)"
  ],
  "class_interval.A8.baz (method)": [ "_test_source (fun)" ],
  "class_interval.A9.f (method)": [ "_test_source (fun)" ],
  "class_interval.B0.m0 (method)": [ "class_interval.A0.m1 (method)" ],
  "class_interval.B1.m0 (method)": [ "class_interval.B1.m1 (method)" ],
  "class_interval.B14.m0 (method)": [ "class_interval.A14.m1 (method)" ],
  "class_interval.B15.m0 (method)": [ "class_interval.A15.m1 (method)" ],
  "class_interval.B16.m0 (method)": [ "class_interval.A16.m1 (method)" ],
  "class_interval.B18.m (method)": [ "class_interval.sink_b (fun)" ],
  "class_interval.B2.m0 (method)": [ "class_interval.A2.m1 (method)" ],
  "class_interval.B21.m1 (method)": [ "class_interval.transformX (fun)" ],
  "class_interval.B22.m1 (method)": [ "class_interval.transformX (fun)" ],
  "class_interval.B24.m1 (method)": [ "_test_source (fun)" ],
  "class_interval.B3.m0 (method)": [ "class_interval.A3.m1 (method)" ],
  "class_interval.B4.m1 (method)": [ "class_interval.A4.m2 (method)" ],
  "class_interval.B5.m0 (method)": [ "class_interval.A5.m1 (method)" ],
  "class_interval.B6.m0 (method)": [
    "_test_source (fun)", "class_interval.E6.m3 (method)",
    "int.__eq__ (method)", "int.__ne__ (method)", "object.__init__ (method)",
    "object.__new__ (method)"
  ],
  "class_interval.B7.bar (method)": [ "_test_source (fun)" ],
  "class_interval.B7.foo (method)": [ "class_interval.B7.bar (method)" ],
  "class_interval.B8.foo (method)": [ "_test_source (fun)" ],
  "class_interval.C0.m2 (method)": [ "_test_sink (fun)" ],
  "class_interval.C1.m2 (method)": [ "_test_sink (fun)" ],
  "class_interval.C12.g (method)": [ "_test_source (fun)" ],
  "class_interval.C13.g (method)": [ "_test_source (fun)" ],
  "class_interval.C14.m2 (method)": [ "_test_source (fun)" ],
  "class_interval.C17.m1 (method)": [ "class_interval.sink_c (fun)" ],
  "class_interval.C18.m (method)": [ "class_interval.B18.m (method)" ],
  "class_interval.C20.m0 (method)": [ "_test_sink (fun)" ],
  "class_interval.C23.m1 (method)": [ "class_interval.add_feature_c (fun)" ],
  "class_interval.C3.m0 (method)": [ "class_interval.A3.m1 (method)" ],
  "class_interval.C3.m2 (method)": [ "_test_sink (fun)" ],
  "class_interval.C4.m3 (method)": [ "_test_sink (fun)" ],
  "class_interval.C6.m2 (method)": [ "class_interval.A6.m1 (method)" ],
  "class_interval.D16.m2 (method)": [ "_test_source (fun)" ],
  "class_interval.D17.m1 (method)": [ "class_interval.sink_c (fun)" ],
  "class_interval.D2.m2 (method)": [ "_test_sink (fun)" ],
  "class_interval.D23.m1 (method)": [ "class_interval.add_feature_d (fun)" ],
  "class_interval.D4.m0 (method)": [ "class_interval.B4.m1 (method)" ],
  "class_interval.D5.m2 (method)": [ "_test_sink (fun)" ],
  "class_interval.D6.m0 (method)": [
    "class_interval.B6.m0 (method)", "object.__new__ (method)",
    "super.__init__ (method)"
  ],
  "class_interval.E15.m2 (method)": [ "_test_source (fun)" ],
  "class_interval.E23.m1 (method)": [ "class_interval.add_feature_e (fun)" ],
  "class_interval.E6.m3 (method)": [ "_test_source (fun)" ],
  "class_interval.abstract_method (fun)": [
    "_test_sink (fun)", "class_interval.A13.f (method)"
  ],
  "class_interval.call_method_via_class_name (fun)": [
    "class_interval.A9.f (method)"
  ],
  "class_interval.canonical_example (fun)": [
    "_test_source (fun)", "class_interval.B0.m0 (method)"
  ],
  "class_interval.issue_precise_tito_intervals (fun)": [
    "_test_sink (fun)", "_test_source (fun)",
    "class_interval.A23.m0 (method)"
  ],
  "class_interval.multi_inheritance_issue (fun)": [
    "_test_sink (fun)", "class_interval.B16.m0 (method)"
  ],
  "class_interval.multi_inheritance_no_issue_one_hop (fun)": [
    "_test_sink (fun)", "class_interval.B14.m0 (method)"
  ],
  "class_interval.multi_inheritance_no_issue_two_hops (fun)": [
    "_test_sink (fun)", "class_interval.B15.m0 (method)"
  ],
  "class_interval.multiple_inheritance (fun)": [
    "_test_source (fun)", "class_interval.B2.m0 (method)"
  ],
  "class_interval.no_call_to_parent_class (fun)": [
    "_test_source (fun)", "class_interval.B1.m0 (method)"
  ],
  "class_interval.no_issue_source_through_staticmethod_tito (fun)": [
    "_test_sink (fun)", "class_interval.A24.m0 (method)"
  ],
  "class_interval.no_issue_taint_transform_with_class_interval (fun)": [
    "_test_source (fun)", "class_interval.A22.m0 (method)",
    "class_interval.sink_d (fun)"
  ],
  "class_interval.no_issue_taint_transform_with_class_interval_for_classmethods (fun)": [
    "_test_source (fun)", "class_interval.A21.m0 (method)",
    "class_interval.sink_d (fun)"
  ],
  "class_interval.propagate_source_empty (fun)": [
    "_test_sink (fun)", "class_interval.A6.m1 (method)"
  ],
  "class_interval.sink_in_subclass (fun)": [
    "_test_source (fun)", "class_interval.B3.m0 (override)"
  ],
  "class_interval.sink_two_hops (fun)": [
    "_test_source (fun)", "class_interval.B5.m0 (method)"
  ],
  "class_interval.source_two_hops (fun)": [
    "_test_source (fun)", "class_interval.D4.m0 (method)"
  ],
  "class_interval.test_class_methods (fun)": [
    "_test_source (fun)", "class_interval.A17.m0 (method)",
    "class_interval.A17.m2 (method)", "object.__init__ (method)",
    "object.__new__ (method)"
  ],
  "class_interval.test_multi_inheritance_parent_call (fun)": [
    "_test_source (fun)", "class_interval.A20.m0 (method)"
  ],
  "class_interval.test_multi_inheritance_parent_issue (fun)": [
    "class_interval.test_multi_inheritance_parent_call (fun)",
    "object.__init__ (method)", "object.__new__ (method)"
  ],
  "class_interval.test_static_methods (fun)": [
    "_test_source (fun)", "object.__init__ (method)",
    "object.__new__ (method)"
  ],
  "class_interval.undetected_issue (fun)": [
    "_test_sink (fun)", "class_interval.A12.f (method)"
  ]
}