@generated
Call dependencies
{
  "class_methods.C.class_method (method)": [ "pysa._test_sink (fun)" ],
  "class_methods.C.one_hop_abstract_class_method (method)": [
    "class_methods.C.abstract_class_method (override)"
  ],
  "class_methods.C.one_hop_abstract_method (method)": [
    "class_methods.C.abstract_method (method)"
  ],
  "class_methods.C.one_hop_class_abstractmethod (method)": [
    "class_methods.C.class_abstractmethod (override)"
  ],
  "class_methods.C.one_hop_class_method (method)": [
    "class_methods.C.class_method (method)"
  ],
  "class_methods.C.one_hop_static_abstractmethod (method)": [
    "class_methods.C.static_abstractmethod (method)"
  ],
  "class_methods.C.static_abstractmethod (method)": [
    "pysa._test_sink (fun)"
  ],
  "class_methods.D.__init__ (method)": [
    "object.__init__ (method)", "object.__new__ (method)",
    "super.__init__ (method)"
  ],
  "class_methods.D.abstract_class_method (method)": [
    "pysa._test_sink (fun)"
  ],
  "class_methods.D.abstract_method (method)": [ "pysa._test_sink (fun)" ],
  "class_methods.D.class_abstractmethod (method)": [
    "pysa._test_sink (fun)"
  ],
  "class_methods.Test.foo (method)": [ "pysa._test_sink (fun)" ],
  "class_methods.bar (fun)": [
    "class_methods.Test.foo (method)", "pysa._test_source (fun)"
  ],
  "class_methods.issue_with_abstract_class_method (fun)": [
    "class_methods.C.one_hop_abstract_class_method (method)",
    "class_methods.C.one_hop_abstract_method (method)",
    "class_methods.C.one_hop_class_abstractmethod (method)",
    "class_methods.C.one_hop_class_method (method)",
    "class_methods.C.one_hop_static_abstractmethod (method)",
    "pysa._test_source (fun)"
  ],
  "class_methods.issue_with_abstract_property (fun)": [
    "class_methods.D.__init__ (method)",
    "class_methods.D.my_abstract_property (method)",
    "class_methods.D.my_abstract_property@setter (method)",
    "object.__new__ (method)", "pysa._test_sink (fun)",
    "pysa._test_source (fun)"
  ],
  "class_methods.test_obscure_class_method_tito (fun)": [
    "class_methods.ObscureClassMethodTito.__init__ (method)",
    "class_methods.ObscureClassMethodTito.method (method)",
    "object.__new__ (method)", "pysa._test_sink (fun)",
    "pysa._test_source (fun)"
  ]
}