@generated
Call dependencies
{
  "class_flows.HasClassmethods._async_results_for_non_empty_query_from_db (method)": [
    "class_flows.HasClassmethods._get_multi_word_results (method)",
    "class_flows.HasClassmethods._get_single_word_results (method)"
  ],
  "class_flows.HasClassmethods._get_multi_word_results (method)": [
    "pysa._test_sink (fun)"
  ],
  "class_flows.HasDecoratedClassmethod.to_sink (method)": [
    "pysa._test_sink (fun)"
  ],
  "class_flows.HasDecoratedClassmethod.to_sink@decorated (method)": [
    "builtins.classmethod.__init__ (method)",
    "builtins.object.__new__ (method)", "contextlib.contextmanager (fun)"
  ],
  "class_flows.global_class_attribute_issue (fun)": [
    "class_flows.C.__class__.tainted_class_attribute (object)",
    "pysa._test_source (fun)"
  ],
  "class_flows.tainted_attribute_flow_issue (fun)": [
    "class_flows.C.tainted_attribute (object)", "pysa._test_source (fun)"
  ],
  "class_flows.tainted_attribute_for_class_not_issue (fun)": [
    "pysa._test_source (fun)"
  ],
  "class_flows.tainted_attribute_through_inheritance_issue (fun)": [
    "class_flows.C.tainted_attribute (object)", "pysa._test_source (fun)"
  ],
  "class_flows.tainted_class_attribute_through_class_issue (fun)": [
    "class_flows.C.__class__.tainted_class_attribute (object)",
    "pysa._test_source (fun)"
  ],
  "class_flows.tainted_class_attribute_through_double_underscore_class_issue (fun)": [
    "class_flows.C.__class__.tainted_class_attribute (object)",
    "pysa._test_source (fun)"
  ],
  "class_flows.tainted_class_attribute_through_instance_not_issue (fun)": [
    "pysa._test_source (fun)"
  ],
  "class_flows.tainted_class_attribute_through_optional_class_issue (fun)": [
    "class_flows.C.__class__.tainted_class_attribute (object)",
    "pysa._test_source (fun)"
  ],
  "class_flows.test_classmethod (fun)": [
    "class_flows.HasClassmethods._async_results_for_non_empty_query_from_db (method)",
    "pysa._test_source (fun)"
  ],
  "class_flows.test_decorated_classmethod (fun)": [
    "class_flows.HasDecoratedClassmethod.to_sink (method)",
    "pysa._test_source (fun)"
  ],
  "class_flows.untainted_flow_not_issue (fun)": [ "pysa._test_source (fun)" ]
}