@generated
Call dependencies
{
  "closure_models.captured_variable_model_both_generation_parameter_source (fun)": [
    "_test_sink (fun)",
    "closure_models.captured_variable_model_both_generation_parameter_source.model_all_captured_as_generation_and_parameter_sources (fun)"
  ],
  "closure_models.captured_variable_model_both_generation_parameter_source.model_all_captured_as_generation_and_parameter_sources (fun)": [
    "_test_sink (fun)"
  ],
  "closure_models.captured_variable_model_generation_source (fun)": [
    "_test_sink (fun)",
    "closure_models.captured_variable_model_generation_source.model_all_captured_as_generation_sources (fun)"
  ],
  "closure_models.captured_variable_model_generation_source.model_all_captured_as_generation_sources (fun)": [
    "_test_sink (fun)"
  ],
  "closure_models.captured_variable_model_parameter_source (fun)": [
    "_test_sink (fun)",
    "closure_models.captured_variable_model_parameter_source.model_all_captured_as_parameter_sources (fun)"
  ],
  "closure_models.captured_variable_model_parameter_source.model_all_captured_as_parameter_sources (fun)": [
    "_test_sink (fun)"
  ],
  "closure_models.captured_variable_model_sink (fun)": [
    "_test_source (fun)",
    "closure_models.captured_variable_model_sink.model_all_captured_as_sinks (fun)"
  ],
  "closure_models.captured_variable_model_tito (fun)": [
    "_test_sink (fun)", "_test_source (fun)",
    "closure_models.captured_variable_model_tito.model_all_captured_as_tito (fun)"
  ],
  "closure_models.inner_sink_wrapper (fun)": [
    "_test_source (fun)",
    "closure_models.inner_sink_wrapper.inner_sink (fun)"
  ],
  "closure_models.test (fun)": [
    "_test_source (fun)",
    "closure_models.Reclassification.reclassify (method)",
    "closure_models.reclassify (fun)[formal(inner, position=0)=closure_models.outer (fun)]",
    "closure_models.reclassify (fun)[formal(inner, position=0)=closure_models.test.return_model_query_tito (fun)]",
    "closure_models.reclassify (fun)[formal(inner, position=0)=closure_models.test.return_model_taint (fun)]",
    "closure_models.reclassify (fun)[formal(inner, position=0)=closure_models.test.return_model_taint_tito (fun)]",
    "closure_models.reclassify (fun)[formal(inner, position=0)=closure_models.test.return_taint (fun)]"
  ],
  "closure_models.test.return_model_query_tito (fun)": [
    "closure_models.use_source (fun)"
  ],
  "closure_models.test.return_model_taint_tito (fun)": [
    "closure_models.use_source (fun)"
  ],
  "closure_models.test.return_taint (fun)": [ "_test_source (fun)" ],
  "closure_models.test_dsl_decorator_source.decorated_local_function_capturing_local_variable (fun)": [
    "_test_sink (fun)"
  ],
  "closure_models.test_dsl_decorator_source.decorated_local_function_capturing_local_variable@decorated (fun)": [
    "closure_models.some_decorator (fun)[formal(func, position=0)=closure_models.test_dsl_decorator_source.decorated_local_function_capturing_local_variable (fun)]"
  ],
  "closure_models.test_dsl_source.local_function_capturing_local_variable (fun)": [
    "_test_sink (fun)"
  ],
  "closure_models.test_tito_transform (fun)": [
    "_test_source (fun)",
    "closure_models.Reclassification.reclassify (method)",
    "closure_models.reclassify (fun)[formal(inner, position=0)=closure_models.test_tito_transform.return_model_query_tito (fun)]",
    "closure_models.reclassify (fun)[formal(inner, position=0)=closure_models.test_tito_transform.return_model_taint_tito (fun)]"
  ],
  "closure_models.test_tito_transform.return_model_query_tito (fun)": [
    "closure_models.use_source (fun)"
  ],
  "closure_models.test_tito_transform.return_model_taint_tito (fun)": [
    "closure_models.use_source (fun)"
  ]
}