@generated
Call dependencies
{
  "constructors.BaseConstructor.__init__ (method)": [
    "pysa._test_source (fun)"
  ],
  "constructors.BothNewAndInit.__init__ (method)": [
    "pysa._test_sink (fun)"
  ],
  "constructors.BothNewAndInit.__new__ (method)": [
    "object.__new__ (method)", "pysa._test_source (fun)",
    "super.__init__ (method)"
  ],
  "constructors.ChildWithNew.__new__ (method)": [
    "object.__new__ (method)", "pysa._test_sink (fun)"
  ],
  "constructors.DerivedConstructor.__init__ (method)": [
    "constructors.BaseConstructor.__init__ (method)",
    "object.__new__ (method)", "super.__init__ (method)"
  ],
  "constructors.DerivedConstructorTitoModelQuery.__init__ (method)": [
    "constructors.ConstructorTitoModelQuery.__init__ (method)",
    "object.__new__ (method)", "super.__init__ (method)"
  ],
  "constructors.DerivedConstructorWithTitoModel.__init__ (method)": [
    "constructors.ConstructorWithTitoModel.__init__ (method)",
    "object.__new__ (method)", "super.__init__ (method)"
  ],
  "constructors.ParentWithNoConstructor.__init__ (method)": [
    "object.__init__ (method)", "object.__new__ (method)",
    "super.__init__ (method)"
  ],
  "constructors.ParentWithObscureConstructor.__init__ (method)": [
    "constructors.ConstructorObscure.__init__ (method)",
    "object.__new__ (method)", "super.__init__ (method)"
  ],
  "constructors.SanitizeReturn.__init__ (method)": [
    "pysa._test_source (fun)"
  ],
  "constructors.SanitizeSingleTraceSource.__init__ (method)": [
    "pysa._test_source (fun)"
  ],
  "constructors.SanitizeTitoKindSpecific.__init__ (method)": [
    "pysa._test_source (fun)"
  ],
  "constructors.SomeAPI.$class_toplevel (method)": [ "str.__str__ (method)" ],
  "constructors.SomeAPI.async_get_authenticated_user (method)": [
    "eval (fun)"
  ],
  "constructors.SomeAPI.from_default_keys (method)": [
    "constructors.SomeAPI.__init__ (method)", "object.__new__ (method)"
  ],
  "constructors.SourceInConstructor.__init__ (method)": [
    "pysa._test_source (fun)"
  ],
  "constructors.test_both_new_and_init_callgraph (fun)": [
    "constructors.BothNewAndInit.__init__ (method)",
    "constructors.BothNewAndInit.__new__ (method)"
  ],
  "constructors.test_class_stub (fun)": [
    "object.__init__ (method)", "object.__new__ (method)",
    "pysa._test_sink (fun)", "pysa._test_source (fun)"
  ],
  "constructors.test_construction (fun)": [
    "constructors.SomeAPI.async_get_authenticated_user (method)",
    "constructors.SomeAPI.from_default_keys (method)",
    "dict.__getitem__ (method)"
  ],
  "constructors.test_constructor_with_source_model (fun)": [
    "constructors.ConstructorWithSourceModel.__init__ (method)",
    "object.__new__ (method)", "pysa._test_sink (fun)"
  ],
  "constructors.test_constructor_with_tito_model (fun)": [
    "constructors.DerivedConstructorWithTitoModel.__init__ (method)",
    "object.__new__ (method)", "pysa._test_sink (fun)",
    "pysa._test_source (fun)"
  ],
  "constructors.test_constructor_with_tito_model_query (fun)": [
    "constructors.DerivedConstructorTitoModelQuery.__init__ (method)",
    "object.__new__ (method)", "pysa._test_sink (fun)",
    "pysa._test_source (fun)"
  ],
  "constructors.test_init_model (fun)": [
    "constructors.InitWithModel.__init__ (method)",
    "object.__new__ (method)", "pysa._test_sink (fun)",
    "pysa._test_source (fun)"
  ],
  "constructors.test_new_model (fun)": [
    "constructors.NewWithModel.__new__ (method)", "object.__init__ (method)",
    "pysa._test_sink (fun)", "pysa._test_source (fun)"
  ],
  "constructors.test_new_thing (fun)": [
    "constructors.ChildWithNew.__new__ (method)",
    "constructors.ParentWithInit.__init__ (method)",
    "pysa._test_source (fun)"
  ],
  "constructors.test_parent_with_no_constructor (fun)": [
    "constructors.ParentWithNoConstructor.__init__ (method)",
    "object.__new__ (method)", "pysa._test_sink (fun)",
    "pysa._test_source (fun)"
  ],
  "constructors.test_parent_with_obscure_constructor (fun)": [
    "constructors.ParentWithObscureConstructor.__init__ (method)",
    "object.__new__ (method)", "pysa._test_sink (fun)",
    "pysa._test_source (fun)"
  ],
  "constructors.test_source_in_constructor (fun)": [
    "constructors.SourceInConstructor.__init__ (method)",
    "object.__new__ (method)", "pysa._test_sink (fun)"
  ]
}