@generated
Call dependencies
cross_repository.cross_repository_anchor_sink (fun) -> []
cross_repository.cross_repository_source (fun) -> [_test_sink (fun)]
cross_repository.test_cross_repository_anchor (fun) -> [_test_source (fun) cross_repository.cross_repository_anchor_sink (fun)]
cross_repository.test_propagate_cross_repository_sink_once (fun) -> [cross_repository.reaches_crtex_sink (fun)]
cross_repository.test_propagate_cross_repository_sink_twice (fun) -> [cross_repository.test_propagate_cross_repository_sink_once (fun)]
cross_repository.test_propagate_cross_repository_source_once (fun) -> [cross_repository.returns_crtex_source (fun)]
cross_repository.test_propagate_cross_repository_source_twice (fun) -> [cross_repository.test_propagate_cross_repository_source_once (fun)]
cross_repository.$toplevel (fun) -> []
cross_repository.reaches_crtex_sink (fun) -> []
cross_repository.returns_crtex_source (fun) -> []
cross_repository.test (fun) -> [_test_sink (fun) cross_repository.returns_crtex_source (fun)]
