@generated
Call dependencies
dataclass_taint.DataClassWIthInit::__init__ (method) -> [__test_sink (fun)]
dataclass_taint.WeirdDataClass::__init__ (method) -> [object::__setattr__ (method)]
dataclass_taint.bad_is_tainted (fun) -> [__test_sink (fun) __test_source (fun) dataclass_taint.DataClass::__init__ (method) object::__new__ (method)]
dataclass_taint.benign_is_untainted (fun) -> [__test_sink (fun) __test_source (fun) dataclass_taint.DataClass::__init__ (method) object::__new__ (method)]
dataclass_taint.issue_in_dataclass_constructor (fun) -> [__test_source (fun) dataclass_taint.DataClassWIthInit::__init__ (method) object::__new__ (method)]
dataclass_taint.test_dataclass_with_other_source (fun) -> [__test_sink (fun)]
dataclass_taint.test_dataclass_with_source (fun) -> [__test_sink (fun)]
dataclass_taint.test_weird_dataclass_taint (fun) -> [dataclass_taint.WeirdDataClass::__init__ (method) object::__new__ (method)]
