@generated
Call dependencies
{
  "decorator.Foo.bar (method)": [ "builtins.print (fun)" ],
  "decorator.Foo.bar@decorated (method)": [
    "decorator.with_logging_args_kwargs (fun)[formal(f, position=0)=decorator.Foo.bar (method)]",
    "decorator.with_logging_args_kwargs_no_sink (fun)[formal(f, position=0)=decorator.with_logging_args_kwargs.inner (fun)]"
  ],
  "decorator.Foo.foo (method)": [ "decorator.Foo.sink_method (method)" ],
  "decorator.Foo.foo@decorated (method)": [
    "decorator.with_logging_args_kwargs_no_sink (fun)[formal(f, position=0)=decorator.Foo.foo (method)]"
  ],
  "decorator.Foo.self_has_generic_type (method)": [
    "decorator.with_logging_args_kwargs_no_sink.inner (fun)"
  ],
  "decorator.Foo.self_has_generic_type@decorated (method)": [
    "decorator.with_logging_args_kwargs_no_sink (fun)[formal(f, position=0)=decorator.Foo.self_has_generic_type (method)]"
  ],
  "decorator.Foo.sink_method (method)": [
    "builtins.print (fun)", "pysa._test_sink (fun)"
  ],
  "decorator.Foo.some_class_method (method)": [
    "builtins.object.__init__ (method)", "builtins.object.__new__ (method)",
    "decorator.Foo.sink_method (method)"
  ],
  "decorator.Foo.some_class_method@decorated (method)": [
    "builtins.classmethod.__init__ (method)",
    "builtins.object.__new__ (method)",
    "decorator.with_logging_args_kwargs_no_sink (fun)[formal(f, position=0)=decorator.Foo.some_class_method (method)]"
  ],
  "decorator.StringWrapper.__add__ (method)": [
    "builtins.object.__new__ (method)", "builtins.str.__add__ (method)",
    "decorator.StringWrapper.__init__ (method)", "pysa._test_sink (fun)"
  ],
  "decorator.StringWrapper.__add__@decorated (method)": [
    "decorator.no_op_decorator (fun)[formal(f, position=0)=decorator.StringWrapper.__add__ (method)]"
  ],
  "decorator.add_return_source.inner (fun)": [ "pysa._test_source (fun)" ],
  "decorator.conditional_decorator_factory.add_sink.inner (fun)": [
    "pysa._test_sink (fun)"
  ],
  "decorator.decorated (fun)": [ "pysa._test_sink (fun)" ],
  "decorator.decorated@decorated (fun)": [
    "decorator._strip_first_parameter_ (fun)[formal(f, position=0)=decorator.decorated (fun)]"
  ],
  "decorator.foo (fun)": [ "builtins.print (fun)" ],
  "decorator.foo@decorated (fun)": [
    "decorator.with_logging (fun)[formal(f, position=0)=decorator.foo (fun)]"
  ],
  "decorator.foo_args_kwargs (fun)": [ "builtins.print (fun)" ],
  "decorator.foo_args_kwargs@decorated (fun)": [
    "decorator.with_logging_args_kwargs (fun)[formal(f, position=0)=decorator.foo_args_kwargs (fun)]"
  ],
  "decorator.foo_args_kwargs_with_sink (fun)": [ "pysa._test_sink (fun)" ],
  "decorator.foo_args_kwargs_with_sink@decorated (fun)": [
    "decorator.with_logging_args_kwargs_no_sink (fun)[formal(f, position=0)=decorator.foo_args_kwargs_with_sink (fun)]"
  ],
  "decorator.foo_async (fun)": [ "builtins.print (fun)" ],
  "decorator.foo_async@decorated (fun)": [
    "decorator.with_logging_async (fun)[formal(f, position=0)=decorator.foo_async (fun)]"
  ],
  "decorator.foo_log_first_parameter (fun)": [ "builtins.print (fun)" ],
  "decorator.foo_log_first_parameter@decorated (fun)": [
    "decorator.with_logging_first_parameter (fun)[formal(f, position=0)=decorator.foo_log_first_parameter (fun)]"
  ],
  "decorator.foo_using_decorator_factory (fun)": [ "builtins.print (fun)" ],
  "decorator.foo_using_decorator_factory@decorated (fun)": [
    "decorator.with_named_logger (fun)",
    "decorator.with_named_logger._inner_decorator (fun)[formal(f, position=0)=decorator.foo_using_decorator_factory (fun)]"
  ],
  "decorator.foo_with_helper_function (fun)": [ "builtins.print (fun)" ],
  "decorator.foo_with_helper_function@decorated (fun)": [
    "decorator.with_logging_helper_functions (fun)[formal(f, position=0)=decorator.foo_with_helper_function (fun)]"
  ],
  "decorator.foo_with_shady_decorators (fun)": [ "builtins.print (fun)" ],
  "decorator.foo_with_shady_decorators@decorated (fun)": [
    "decorator.fails_to_apply (fun)[formal(f, position=0)=decorator.foo_with_shady_decorators (fun)]",
    "decorator.fails_to_apply (fun)[formal(f, position=0)=decorator.with_logging_sink.inner (fun)]",
    "decorator.fails_to_apply (fun)[formal(f, position=0)=decorator.with_logging_source.inner (fun)]",
    "decorator.with_logging_sink (fun)",
    "decorator.with_logging_source (fun)"
  ],
  "decorator.foo_with_sink (fun)": [
    "builtins.print (fun)", "pysa._test_sink (fun)"
  ],
  "decorator.foo_with_sink@decorated (fun)": [
    "decorator.with_logging_no_sink (fun)[formal(f, position=0)=decorator.foo_with_sink (fun)]"
  ],
  "decorator.issue_str_wrapper (fun)": [
    "builtins.object.__new__ (method)",
    "decorator.StringWrapper.__init__ (method)", "pysa._test_source (fun)"
  ],
  "decorator.issue_via_conditional_decorator_factory (fun)": [
    "decorator.conditional_decorator_factory.add_sink.inner (fun)",
    "decorator.sink_via_conditional_decorator_factory (fun)",
    "pysa._test_source (fun)"
  ],
  "decorator.issue_via_conditional_no_op_decorator_factory (fun)": [
    "decorator.sink_via_conditional_no_op_decorator_factory (fun)",
    "pysa._test_source (fun)"
  ],
  "decorator.issue_via_no_op_decorator (fun)": [ "pysa._test_source (fun)" ],
  "decorator.issue_via_no_op_decorator_factory (fun)": [
    "decorator.sink_via_no_op_decorator_factory (fun)",
    "pysa._test_source (fun)"
  ],
  "decorator.issue_via_trivial_decorator (fun)": [
    "decorator.trivial_decorator.inner (fun)", "pysa._test_source (fun)"
  ],
  "decorator.main (fun)": [
    "builtins.object.__init__ (method)", "builtins.object.__new__ (method)",
    "decorator.foo_using_decorator_factory (fun)",
    "decorator.with_logging.inner (fun)",
    "decorator.with_logging_args_kwargs.inner (fun)",
    "decorator.with_logging_args_kwargs_no_sink.inner (fun)",
    "decorator.with_logging_async.inner (fun)",
    "decorator.with_logging_first_parameter.inner (fun)",
    "decorator.with_logging_helper_functions.inner (fun)",
    "decorator.with_logging_no_sink.inner (fun)",
    "decorator.with_named_logger._inner_decorator.inner (fun)",
    "pysa._test_source (fun)"
  ],
  "decorator.return_source_via_decorator@decorated (fun)": [
    "decorator.add_return_source (fun)[formal(callable, position=0)=decorator.return_source_via_decorator (fun)]"
  ],
  "decorator.second_parameter_source_inlineable_decorator (fun)": [
    "pysa._test_sink (fun)"
  ],
  "decorator.second_parameter_source_inlineable_decorator@decorated (fun)": [
    "decorator.trivial_decorator (fun)[formal(f, position=0)=decorator.second_parameter_source_inlineable_decorator (fun)]"
  ],
  "decorator.second_parameter_source_inlineable_decorator_with_inner (fun)": [
    "decorator.second_parameter_source_inlineable_decorator_with_inner.inner (fun)"
  ],
  "decorator.second_parameter_source_inlineable_decorator_with_inner.inner (fun)": [
    "pysa._test_sink (fun)"
  ],
  "decorator.second_parameter_source_inlineable_decorator_with_inner@decorated (fun)": [
    "decorator.trivial_decorator (fun)[formal(f, position=0)=decorator.second_parameter_source_inlineable_decorator_with_inner (fun)]"
  ],
  "decorator.second_parameter_source_with_non_inlineable_decorator (fun)": [
    "pysa._test_sink (fun)"
  ],
  "decorator.second_parameter_source_with_non_inlineable_decorator@decorated (fun)": [
    "decorator.discard_second_parameter_non_inlineable (fun)[formal(f, position=0)=decorator.second_parameter_source_with_non_inlineable_decorator (fun)]"
  ],
  "decorator.sink_via_conditional_decorator_factory (fun)": [
    "builtins.print (fun)"
  ],
  "decorator.sink_via_conditional_decorator_factory@decorated (fun)": [
    "decorator.conditional_decorator_factory (fun)",
    "decorator.conditional_decorator_factory.add_sink (fun)[formal(f, position=0)=decorator.sink_via_conditional_decorator_factory (fun)]",
    "decorator.conditional_decorator_factory.identity (fun)[formal(f, position=0)=decorator.sink_via_conditional_decorator_factory (fun)]"
  ],
  "decorator.sink_via_conditional_no_op_decorator_factory (fun)": [
    "pysa._test_sink (fun)"
  ],
  "decorator.sink_via_conditional_no_op_decorator_factory@decorated (fun)": [
    "decorator.conditional_no_op_decorator_factory (fun)",
    "decorator.conditional_no_op_decorator_factory.inner_false (fun)[formal(f, position=0)=decorator.sink_via_conditional_no_op_decorator_factory (fun)]",
    "decorator.conditional_no_op_decorator_factory.inner_true (fun)[formal(f, position=0)=decorator.sink_via_conditional_no_op_decorator_factory (fun)]"
  ],
  "decorator.sink_via_no_op_decorator (fun)": [ "pysa._test_sink (fun)" ],
  "decorator.sink_via_no_op_decorator@decorated (fun)": [
    "decorator.no_op_decorator (fun)[formal(f, position=0)=decorator.sink_via_no_op_decorator (fun)]"
  ],
  "decorator.sink_via_no_op_decorator_factory (fun)": [
    "pysa._test_sink (fun)"
  ],
  "decorator.sink_via_no_op_decorator_factory@decorated (fun)": [
    "decorator.no_op_decorator_factory (fun)",
    "decorator.no_op_decorator_factory.inner (fun)[formal(f, position=0)=decorator.sink_via_no_op_decorator_factory (fun)]"
  ],
  "decorator.sink_via_trivial_decorator (fun)": [ "pysa._test_sink (fun)" ],
  "decorator.sink_via_trivial_decorator@decorated (fun)": [
    "decorator.trivial_decorator (fun)[formal(f, position=0)=decorator.sink_via_trivial_decorator (fun)]"
  ],
  "decorator.test_parameter_default_value (fun)": [
    "decorator.add_return_source.inner (fun)", "pysa._test_sink (fun)"
  ],
  "decorator.using_decorated (fun)": [
    "decorator._strip_first_parameter_.inner (fun)"
  ],
  "decorator.with_logging.inner (fun)": [ "pysa._test_sink (fun)" ],
  "decorator.with_logging_args_kwargs.inner (fun)": [
    "pysa._test_sink (fun)"
  ],
  "decorator.with_logging_async.inner (fun)": [
    "builtins.isinstance (fun)", "pysa._test_sink (fun)"
  ],
  "decorator.with_logging_first_parameter.inner (fun)": [
    "builtins.int.__ne__ (method)", "pysa._test_sink (fun)"
  ],
  "decorator.with_logging_helper_functions.after (fun)": [
    "builtins.print (fun)", "pysa._test_sink (fun)"
  ],
  "decorator.with_logging_helper_functions.before (fun)": [
    "builtins.print (fun)"
  ],
  "decorator.with_logging_helper_functions.inner (fun)": [
    "builtins.isinstance (fun)", "builtins.print (fun)",
    "decorator.with_logging_helper_functions.after (fun)",
    "decorator.with_logging_helper_functions.before (fun)"
  ],
  "decorator.with_logging_sink.inner (fun)": [ "pysa._test_sink (fun)" ],
  "decorator.with_logging_source.inner (fun)": [
    "builtins.str.__add__ (method)", "pysa._test_source (fun)"
  ],
  "decorator.with_named_logger._inner_decorator.inner (fun)": [
    "builtins.print (fun)", "pysa._test_sink (fun)"
  ]
}