@generated
Call dependencies
{
  "decorator_location.Foo.return_source (method)": [
    "pysa._test_source (fun)"
  ],
  "decorator_location.call_return_foo (fun)": [
    "decorator_location.identity.inner (fun)[captured_variable(f, decorator_location.identity)=decorator_location.return_foo (fun)]",
    "pysa._test_sink (fun)"
  ],
  "decorator_location.decorated_ignore_then_skip_decorator (fun)": [
    "pysa._test_sink (fun)"
  ],
  "decorator_location.decorated_ignore_this_decorator (fun)": [
    "pysa._test_sink (fun)"
  ],
  "decorator_location.decorated_ignore_this_decorator_class (fun)": [
    "pysa._test_sink (fun)"
  ],
  "decorator_location.decorated_ignore_this_decorator_factory (fun)": [
    "pysa._test_sink (fun)"
  ],
  "decorator_location.decorated_logging2_skip_this_decorator (fun)": [
    "pysa._test_sink (fun)"
  ],
  "decorator_location.decorated_logging2_skip_this_decorator@decorated (fun)": [
    "decorator_location.skip_this_decorator (fun)",
    "decorator_location.with_logging2 (fun)[formal(f, position=0)=decorator_location.decorated_logging2_skip_this_decorator (fun)]"
  ],
  "decorator_location.decorated_logging_ignore_this_decorator (fun)": [
    "pysa._test_sink (fun)"
  ],
  "decorator_location.decorated_logging_ignore_this_decorator@decorated (fun)": [
    "decorator_location.ignore_this_decorator (fun)",
    "decorator_location.with_logging (fun)[formal(f, position=0)=decorator_location.decorated_logging_ignore_this_decorator (fun)]"
  ],
  "decorator_location.decorated_logging_logging2 (fun)": [
    "pysa._test_sink (fun)"
  ],
  "decorator_location.decorated_logging_logging2@decorated (fun)": [
    "decorator_location.with_logging (fun)[formal(f, position=0)=decorator_location.with_logging2.inner (fun)[captured_variable(f, decorator_location.with_logging2)=decorator_location.decorated_logging_logging2 (fun)]]",
    "decorator_location.with_logging2 (fun)[formal(f, position=0)=decorator_location.decorated_logging_logging2 (fun)]"
  ],
  "decorator_location.decorated_skip_this_decorator (fun)": [
    "pysa._test_sink (fun)"
  ],
  "decorator_location.handle_request (fun)": [ "pysa._test_sink (fun)" ],
  "decorator_location.handle_request@decorated (fun)": [
    "decorator_location.pass_local_variable_to_x (fun)[formal(f, position=0)=decorator_location.handle_request (fun)]"
  ],
  "decorator_location.identity.inner (fun)[captured_variable(f, decorator_location.identity)=decorator_location.return_foo (fun)]": [
    "decorator_location.return_foo (fun)"
  ],
  "decorator_location.ignore_this_decorator_factory.decorator.inner (fun)": [
    "builtins.int.__add__ (method)"
  ],
  "decorator_location.main (fun)": [
    "decorator_location.call_return_foo (fun)",
    "decorator_location.decorated_ignore_then_skip_decorator (fun)",
    "decorator_location.decorated_ignore_this_decorator (fun)",
    "decorator_location.decorated_ignore_this_decorator_class (fun)",
    "decorator_location.decorated_ignore_this_decorator_factory (fun)",
    "decorator_location.decorated_skip_this_decorator (fun)",
    "decorator_location.pass_local_variable_to_x.inner (fun)[captured_variable(f, decorator_location.pass_local_variable_to_x)=decorator_location.handle_request (fun)]",
    "decorator_location.with_logging.inner (fun)[captured_variable(f, decorator_location.with_logging)=decorator_location.decorated_logging_ignore_this_decorator (fun)]",
    "decorator_location.with_logging.inner (fun)[captured_variable(f, decorator_location.with_logging)=decorator_location.with_logging2.inner (fun)[captured_variable(f, decorator_location.with_logging2)=decorator_location.decorated_logging_logging2 (fun)]]",
    "decorator_location.with_logging2.inner (fun)[captured_variable(f, decorator_location.with_logging2)=decorator_location.decorated_logging2_skip_this_decorator (fun)]",
    "pysa._test_source (fun)"
  ],
  "decorator_location.pass_local_variable_to_x.inner (fun)": [
    "pysa._test_sink (fun)"
  ],
  "decorator_location.pass_local_variable_to_x.inner (fun)[captured_variable(f, decorator_location.pass_local_variable_to_x)=decorator_location.handle_request (fun)]": [
    "decorator_location.handle_request (fun)", "pysa._test_sink (fun)"
  ],
  "decorator_location.return_foo (fun)": [
    "builtins.object.__init__ (method)", "builtins.object.__new__ (method)"
  ],
  "decorator_location.return_foo@decorated (fun)": [
    "decorator_location.identity (fun)[formal(f, position=0)=decorator_location.return_foo (fun)]"
  ],
  "decorator_location.skip_this_decorator.inner (fun)": [
    "pysa._test_sink (fun)"
  ],
  "decorator_location.with_logging.inner (fun)": [
    "decorator_location.with_logging.some_helper (fun)",
    "pysa._test_sink (fun)"
  ],
  "decorator_location.with_logging.inner (fun)[captured_variable(f, decorator_location.with_logging)=decorator_location.decorated_logging_ignore_this_decorator (fun)]": [
    "decorator_location.decorated_logging_ignore_this_decorator (fun)",
    "decorator_location.with_logging.some_helper (fun)",
    "pysa._test_sink (fun)"
  ],
  "decorator_location.with_logging.inner (fun)[captured_variable(f, decorator_location.with_logging)=decorator_location.with_logging2.inner (fun)[captured_variable(f, decorator_location.with_logging2)=decorator_location.decorated_logging_logging2 (fun)]]": [
    "decorator_location.with_logging.some_helper (fun)",
    "decorator_location.with_logging2.inner (fun)[captured_variable(f, decorator_location.with_logging2)=decorator_location.decorated_logging_logging2 (fun)]",
    "pysa._test_sink (fun)"
  ],
  "decorator_location.with_logging.some_helper (fun)": [
    "builtins.print (fun)", "pysa._test_sink (fun)"
  ],
  "decorator_location.with_logging2.inner (fun)": [ "pysa._test_sink (fun)" ],
  "decorator_location.with_logging2.inner (fun)[captured_variable(f, decorator_location.with_logging2)=decorator_location.decorated_logging2_skip_this_decorator (fun)]": [
    "decorator_location.decorated_logging2_skip_this_decorator (fun)",
    "pysa._test_sink (fun)"
  ],
  "decorator_location.with_logging2.inner (fun)[captured_variable(f, decorator_location.with_logging2)=decorator_location.decorated_logging_logging2 (fun)]": [
    "decorator_location.decorated_logging_logging2 (fun)",
    "pysa._test_sink (fun)"
  ]
}