@generated
Call dependencies
$local_decorator?foo$__original_function (fun) -> [print (fun)]
$local_decorator?foo$__wrapper (fun) -> [$local_decorator?foo$__original_function (fun) __test_sink (fun)]
$local_decorator?foo_with_sink$__original_function (fun) -> [__test_sink (fun) print (fun)]
$local_decorator?foo_with_sink$__wrapper (fun) -> [$local_decorator?foo_with_sink$__original_function (fun)]
$local_decorator?with_logging$inner (fun) -> [__test_sink (fun)]
$local_decorator?with_logging_no_sink$inner (fun) -> []
decorator.foo (fun) -> [$local_decorator?foo$__wrapper (fun)]
decorator.foo_with_sink (fun) -> [$local_decorator?foo_with_sink$__wrapper (fun)]
decorator.main (fun) -> [__test_source (fun) decorator.foo (fun) decorator.foo_with_sink (fun)]
decorator.with_logging (fun) -> []
decorator.with_logging_no_sink (fun) -> []
