@generated
Call dependencies
{
  "decorator.$toplevel (fun)": [
    "pyre_extensions.ParameterSpecification (fun)"
  ],
  "decorator.Foo.bar (method)": [
    "decorator.Foo.bar._inlined_with_logging_args_kwargs_no_sink2 (fun)",
    "decorator.Foo.bar._inlined_with_logging_args_kwargs_no_sink2 (fun)[local($local_decorator?Foo?bar$_inlined_with_logging_args_kwargs)=decorator.Foo.bar._inlined_with_logging_args_kwargs (fun)[local($local_decorator?Foo?bar$_inlined_with_logging_args_kwargs_no_sink)=decorator.Foo.bar._inlined_with_logging_args_kwargs_no_sink (fun)[local($local_decorator?Foo?bar$_original_function)=decorator.Foo.bar._original_function (fun)]]]"
  ],
  "decorator.Foo.bar._inlined_with_logging_args_kwargs (fun)": [
    "_test_sink (fun)",
    "decorator.Foo.bar._inlined_with_logging_args_kwargs_no_sink (fun)"
  ],
  "decorator.Foo.bar._inlined_with_logging_args_kwargs (fun)[local($local_decorator?Foo?bar$_inlined_with_logging_args_kwargs_no_sink)=decorator.Foo.bar._inlined_with_logging_args_kwargs_no_sink (fun)[local($local_decorator?Foo?bar$_original_function)=decorator.Foo.bar._original_function (fun)]]": [
    "_test_sink (fun)",
    "decorator.Foo.bar._inlined_with_logging_args_kwargs_no_sink (fun)",
    "decorator.Foo.bar._inlined_with_logging_args_kwargs_no_sink (fun)[local($local_decorator?Foo?bar$_original_function)=decorator.Foo.bar._original_function (fun)]"
  ],
  "decorator.Foo.bar._inlined_with_logging_args_kwargs_no_sink (fun)": [
    "decorator.Foo.bar._original_function (fun)"
  ],
  "decorator.Foo.bar._inlined_with_logging_args_kwargs_no_sink (fun)[local($local_decorator?Foo?bar$_original_function)=decorator.Foo.bar._original_function (fun)]": [
    "decorator.Foo.bar._original_function (fun)"
  ],
  "decorator.Foo.bar._inlined_with_logging_args_kwargs_no_sink2 (fun)": [
    "decorator.Foo.bar._inlined_with_logging_args_kwargs (fun)"
  ],
  "decorator.Foo.bar._inlined_with_logging_args_kwargs_no_sink2 (fun)[local($local_decorator?Foo?bar$_inlined_with_logging_args_kwargs)=decorator.Foo.bar._inlined_with_logging_args_kwargs (fun)[local($local_decorator?Foo?bar$_inlined_with_logging_args_kwargs_no_sink)=decorator.Foo.bar._inlined_with_logging_args_kwargs_no_sink (fun)[local($local_decorator?Foo?bar$_original_function)=decorator.Foo.bar._original_function (fun)]]]": [
    "decorator.Foo.bar._inlined_with_logging_args_kwargs (fun)",
    "decorator.Foo.bar._inlined_with_logging_args_kwargs (fun)[local($local_decorator?Foo?bar$_inlined_with_logging_args_kwargs_no_sink)=decorator.Foo.bar._inlined_with_logging_args_kwargs_no_sink (fun)[local($local_decorator?Foo?bar$_original_function)=decorator.Foo.bar._original_function (fun)]]"
  ],
  "decorator.Foo.bar._original_function (fun)": [ "print (fun)" ],
  "decorator.Foo.foo (method)": [
    "decorator.Foo.foo._inlined_with_logging_args_kwargs_no_sink (fun)",
    "decorator.Foo.foo._inlined_with_logging_args_kwargs_no_sink (fun)[local($local_decorator?Foo?foo$_original_function)=decorator.Foo.foo._original_function (fun)]"
  ],
  "decorator.Foo.foo._inlined_with_logging_args_kwargs_no_sink (fun)": [
    "decorator.Foo.foo._original_function (fun)"
  ],
  "decorator.Foo.foo._inlined_with_logging_args_kwargs_no_sink (fun)[local($local_decorator?Foo?foo$_original_function)=decorator.Foo.foo._original_function (fun)]": [
    "decorator.Foo.foo._original_function (fun)"
  ],
  "decorator.Foo.foo._original_function (fun)": [
    "decorator.Foo.sink_method (method)"
  ],
  "decorator.Foo.self_has_generic_type (method)": [
    "decorator.Foo.self_has_generic_type._inlined_with_logging_args_kwargs_no_sink (fun)",
    "decorator.Foo.self_has_generic_type._inlined_with_logging_args_kwargs_no_sink (fun)[local($local_decorator?Foo?self_has_generic_type$_original_function)=decorator.Foo.self_has_generic_type._original_function (fun)]"
  ],
  "decorator.Foo.self_has_generic_type._inlined_with_logging_args_kwargs_no_sink (fun)": [
    "decorator.Foo.self_has_generic_type._original_function (fun)"
  ],
  "decorator.Foo.self_has_generic_type._inlined_with_logging_args_kwargs_no_sink (fun)[local($local_decorator?Foo?self_has_generic_type$_original_function)=decorator.Foo.self_has_generic_type._original_function (fun)]": [
    "decorator.Foo.self_has_generic_type._original_function (fun)"
  ],
  "decorator.Foo.self_has_generic_type._original_function (fun)": [
    "decorator.Foo.bar (method)"
  ],
  "decorator.Foo.sink_method (method)": [ "_test_sink (fun)", "print (fun)" ],
  "decorator.Foo.some_class_method (method)": [
    "decorator.Foo.some_class_method._inlined_with_logging_args_kwargs_no_sink (fun)",
    "decorator.Foo.some_class_method._inlined_with_logging_args_kwargs_no_sink (fun)[local($local_decorator?Foo?some_class_method$_original_function)=decorator.Foo.some_class_method._original_function (fun)]"
  ],
  "decorator.Foo.some_class_method._inlined_with_logging_args_kwargs_no_sink (fun)": [
    "decorator.Foo.some_class_method._original_function (fun)"
  ],
  "decorator.Foo.some_class_method._inlined_with_logging_args_kwargs_no_sink (fun)[local($local_decorator?Foo?some_class_method$_original_function)=decorator.Foo.some_class_method._original_function (fun)]": [
    "decorator.Foo.some_class_method._original_function (fun)"
  ],
  "decorator.Foo.some_class_method._original_function (fun)": [
    "decorator.Foo.sink_method (method)", "object.__init__ (method)",
    "object.__new__ (method)"
  ],
  "decorator.foo (fun)": [
    "decorator.foo._inlined_with_logging (fun)",
    "decorator.foo._inlined_with_logging (fun)[local($local_decorator?foo$_original_function)=decorator.foo._original_function (fun)]"
  ],
  "decorator.foo._inlined_with_logging (fun)": [
    "_test_sink (fun)", "decorator.foo._original_function (fun)"
  ],
  "decorator.foo._inlined_with_logging (fun)[local($local_decorator?foo$_original_function)=decorator.foo._original_function (fun)]": [
    "_test_sink (fun)", "decorator.foo._original_function (fun)"
  ],
  "decorator.foo._original_function (fun)": [ "print (fun)" ],
  "decorator.foo_args_kwargs (fun)": [
    "decorator.foo_args_kwargs._inlined_with_logging_args_kwargs (fun)",
    "decorator.foo_args_kwargs._inlined_with_logging_args_kwargs (fun)[local($local_decorator?foo_args_kwargs$_original_function)=decorator.foo_args_kwargs._original_function (fun)]"
  ],
  "decorator.foo_args_kwargs._inlined_with_logging_args_kwargs (fun)": [
    "_test_sink (fun)", "decorator.foo_args_kwargs._original_function (fun)"
  ],
  "decorator.foo_args_kwargs._inlined_with_logging_args_kwargs (fun)[local($local_decorator?foo_args_kwargs$_original_function)=decorator.foo_args_kwargs._original_function (fun)]": [
    "_test_sink (fun)", "decorator.foo_args_kwargs._original_function (fun)"
  ],
  "decorator.foo_args_kwargs._original_function (fun)": [ "print (fun)" ],
  "decorator.foo_args_kwargs_with_sink (fun)": [
    "decorator.foo_args_kwargs_with_sink._inlined_with_logging_args_kwargs_no_sink (fun)",
    "decorator.foo_args_kwargs_with_sink._inlined_with_logging_args_kwargs_no_sink (fun)[local($local_decorator?foo_args_kwargs_with_sink$_original_function)=decorator.foo_args_kwargs_with_sink._original_function (fun)]"
  ],
  "decorator.foo_args_kwargs_with_sink._inlined_with_logging_args_kwargs_no_sink (fun)": [
    "decorator.foo_args_kwargs_with_sink._original_function (fun)"
  ],
  "decorator.foo_args_kwargs_with_sink._inlined_with_logging_args_kwargs_no_sink (fun)[local($local_decorator?foo_args_kwargs_with_sink$_original_function)=decorator.foo_args_kwargs_with_sink._original_function (fun)]": [
    "decorator.foo_args_kwargs_with_sink._original_function (fun)"
  ],
  "decorator.foo_args_kwargs_with_sink._original_function (fun)": [
    "_test_sink (fun)"
  ],
  "decorator.foo_async (fun)": [
    "decorator.foo_async._inlined_with_logging_async (fun)",
    "decorator.foo_async._inlined_with_logging_async (fun)[local($local_decorator?foo_async$_original_function)=decorator.foo_async._original_function (fun)]"
  ],
  "decorator.foo_async._inlined_with_logging_async (fun)": [
    "_test_sink (fun)", "decorator.foo_async._original_function (fun)"
  ],
  "decorator.foo_async._inlined_with_logging_async (fun)[local($local_decorator?foo_async$_original_function)=decorator.foo_async._original_function (fun)]": [
    "_test_sink (fun)", "decorator.foo_async._original_function (fun)"
  ],
  "decorator.foo_async._original_function (fun)": [ "print (fun)" ],
  "decorator.foo_log_first_parameter (fun)": [
    "decorator.foo_log_first_parameter._inlined_with_logging_first_parameter (fun)",
    "decorator.foo_log_first_parameter._inlined_with_logging_first_parameter (fun)[local($local_decorator?foo_log_first_parameter$_original_function)=decorator.foo_log_first_parameter._original_function (fun)]"
  ],
  "decorator.foo_log_first_parameter._inlined_with_logging_first_parameter (fun)": [
    "_test_sink (fun)",
    "decorator.foo_log_first_parameter._original_function (fun)",
    "int.__eq__ (method)", "int.__ne__ (method)"
  ],
  "decorator.foo_log_first_parameter._inlined_with_logging_first_parameter (fun)[local($local_decorator?foo_log_first_parameter$_original_function)=decorator.foo_log_first_parameter._original_function (fun)]": [
    "_test_sink (fun)",
    "decorator.foo_log_first_parameter._original_function (fun)",
    "int.__eq__ (method)", "int.__ne__ (method)"
  ],
  "decorator.foo_log_first_parameter._original_function (fun)": [
    "print (fun)"
  ],
  "decorator.foo_using_decorator_factory (fun)": [
    "decorator.foo_using_decorator_factory._inlined_with_named_logger (fun)",
    "decorator.foo_using_decorator_factory._inlined_with_named_logger (fun)[local($local_decorator?foo_using_decorator_factory$_original_function)=decorator.foo_using_decorator_factory._original_function (fun)]"
  ],
  "decorator.foo_using_decorator_factory._inlined_with_named_logger (fun)": [
    "_test_sink (fun)",
    "decorator.foo_using_decorator_factory._original_function (fun)",
    "print (fun)"
  ],
  "decorator.foo_using_decorator_factory._inlined_with_named_logger (fun)[local($local_decorator?foo_using_decorator_factory$_original_function)=decorator.foo_using_decorator_factory._original_function (fun)]": [
    "_test_sink (fun)",
    "decorator.foo_using_decorator_factory._original_function (fun)",
    "print (fun)"
  ],
  "decorator.foo_using_decorator_factory._original_function (fun)": [
    "print (fun)"
  ],
  "decorator.foo_with_helper_function (fun)": [
    "decorator.foo_with_helper_function._inlined_with_logging_helper_functions (fun)",
    "decorator.foo_with_helper_function._inlined_with_logging_helper_functions (fun)[local($local_decorator?foo_with_helper_function$_original_function)=decorator.foo_with_helper_function._original_function (fun)]"
  ],
  "decorator.foo_with_helper_function._inlined_with_logging_helper_functions (fun)": [
    "decorator.foo_with_helper_function._inlined_with_logging_helper_functions.after (fun)",
    "decorator.foo_with_helper_function._inlined_with_logging_helper_functions.before (fun)",
    "decorator.foo_with_helper_function._original_function (fun)",
    "isinstance (fun)", "print (fun)"
  ],
  "decorator.foo_with_helper_function._inlined_with_logging_helper_functions (fun)[local($local_decorator?foo_with_helper_function$_original_function)=decorator.foo_with_helper_function._original_function (fun)]": [
    "decorator.foo_with_helper_function._inlined_with_logging_helper_functions.after (fun)",
    "decorator.foo_with_helper_function._inlined_with_logging_helper_functions.before (fun)",
    "decorator.foo_with_helper_function._original_function (fun)",
    "isinstance (fun)", "print (fun)"
  ],
  "decorator.foo_with_helper_function._inlined_with_logging_helper_functions.after (fun)": [
    "_test_sink (fun)", "print (fun)"
  ],
  "decorator.foo_with_helper_function._inlined_with_logging_helper_functions.before (fun)": [
    "print (fun)"
  ],
  "decorator.foo_with_helper_function._original_function (fun)": [
    "print (fun)"
  ],
  "decorator.foo_with_shady_decorators (fun)": [
    "decorator.foo_with_shady_decorators._inlined_with_logging_source (fun)",
    "decorator.foo_with_shady_decorators._inlined_with_logging_source (fun)[local($local_decorator?foo_with_shady_decorators$_inlined_with_logging_sink)=decorator.foo_with_shady_decorators._inlined_with_logging_sink (fun)[local($local_decorator?foo_with_shady_decorators$_original_function)=decorator.foo_with_shady_decorators._original_function (fun)]]"
  ],
  "decorator.foo_with_shady_decorators._inlined_with_logging_sink (fun)": [
    "_test_sink (fun)",
    "decorator.foo_with_shady_decorators._original_function (fun)"
  ],
  "decorator.foo_with_shady_decorators._inlined_with_logging_sink (fun)[local($local_decorator?foo_with_shady_decorators$_original_function)=decorator.foo_with_shady_decorators._original_function (fun)]": [
    "_test_sink (fun)",
    "decorator.foo_with_shady_decorators._original_function (fun)"
  ],
  "decorator.foo_with_shady_decorators._inlined_with_logging_source (fun)": [
    "_test_source (fun)",
    "decorator.foo_with_shady_decorators._inlined_with_logging_sink (fun)",
    "str.__add__ (method)"
  ],
  "decorator.foo_with_shady_decorators._inlined_with_logging_source (fun)[local($local_decorator?foo_with_shady_decorators$_inlined_with_logging_sink)=decorator.foo_with_shady_decorators._inlined_with_logging_sink (fun)[local($local_decorator?foo_with_shady_decorators$_original_function)=decorator.foo_with_shady_decorators._original_function (fun)]]": [
    "_test_source (fun)",
    "decorator.foo_with_shady_decorators._inlined_with_logging_sink (fun)",
    "str.__add__ (method)",
    "decorator.foo_with_shady_decorators._inlined_with_logging_sink (fun)[local($local_decorator?foo_with_shady_decorators$_original_function)=decorator.foo_with_shady_decorators._original_function (fun)]"
  ],
  "decorator.foo_with_shady_decorators._original_function (fun)": [
    "print (fun)"
  ],
  "decorator.foo_with_sink (fun)": [
    "decorator.foo_with_sink._inlined_with_logging_no_sink (fun)",
    "decorator.foo_with_sink._inlined_with_logging_no_sink (fun)[local($local_decorator?foo_with_sink$_original_function)=decorator.foo_with_sink._original_function (fun)]"
  ],
  "decorator.foo_with_sink._inlined_with_logging_no_sink (fun)": [
    "decorator.foo_with_sink._original_function (fun)"
  ],
  "decorator.foo_with_sink._inlined_with_logging_no_sink (fun)[local($local_decorator?foo_with_sink$_original_function)=decorator.foo_with_sink._original_function (fun)]": [
    "decorator.foo_with_sink._original_function (fun)"
  ],
  "decorator.foo_with_sink._original_function (fun)": [
    "_test_sink (fun)", "print (fun)"
  ],
  "decorator.main (fun)": [
    "_test_source (fun)", "decorator.foo (fun)",
    "decorator.foo_args_kwargs (fun)",
    "decorator.foo_args_kwargs_with_sink (fun)", "decorator.foo_async (fun)",
    "decorator.foo_log_first_parameter (fun)",
    "decorator.foo_using_decorator_factory (fun)",
    "decorator.foo_with_helper_function (fun)",
    "decorator.foo_with_shady_decorators (fun)",
    "decorator.foo_with_sink (fun)", "decorator.Foo.bar (method)",
    "decorator.Foo.foo (method)",
    "decorator.Foo.self_has_generic_type (method)",
    "decorator.Foo.some_class_method (method)", "object.__init__ (method)",
    "object.__new__ (method)"
  ],
  "decorator.second_parameter_source_inlineable_decorator (fun)": [
    "decorator.second_parameter_source_inlineable_decorator._inlined_no_op_decorator (fun)",
    "decorator.second_parameter_source_inlineable_decorator._inlined_no_op_decorator (fun)[local($local_decorator?second_parameter_source_inlineable_decorator$_original_function)=decorator.second_parameter_source_inlineable_decorator._original_function (fun)]"
  ],
  "decorator.second_parameter_source_inlineable_decorator._inlined_no_op_decorator (fun)": [
    "decorator.second_parameter_source_inlineable_decorator._original_function (fun)"
  ],
  "decorator.second_parameter_source_inlineable_decorator._inlined_no_op_decorator (fun)[local($local_decorator?second_parameter_source_inlineable_decorator$_original_function)=decorator.second_parameter_source_inlineable_decorator._original_function (fun)]": [
    "decorator.second_parameter_source_inlineable_decorator._original_function (fun)"
  ],
  "decorator.second_parameter_source_inlineable_decorator._original_function (fun)": [
    "_test_sink (fun)"
  ],
  "decorator.second_parameter_source_inlineable_decorator_with_inner (fun)": [
    "decorator.second_parameter_source_inlineable_decorator_with_inner._inlined_no_op_decorator (fun)",
    "decorator.second_parameter_source_inlineable_decorator_with_inner._inlined_no_op_decorator (fun)[local($local_decorator?second_parameter_source_inlineable_decorator_with_inner$_original_function)=decorator.second_parameter_source_inlineable_decorator_with_inner._original_function (fun)]"
  ],
  "decorator.second_parameter_source_inlineable_decorator_with_inner._inlined_no_op_decorator (fun)": [
    "decorator.second_parameter_source_inlineable_decorator_with_inner._original_function (fun)"
  ],
  "decorator.second_parameter_source_inlineable_decorator_with_inner._inlined_no_op_decorator (fun)[local($local_decorator?second_parameter_source_inlineable_decorator_with_inner$_original_function)=decorator.second_parameter_source_inlineable_decorator_with_inner._original_function (fun)]": [
    "decorator.second_parameter_source_inlineable_decorator_with_inner._original_function (fun)"
  ],
  "decorator.second_parameter_source_inlineable_decorator_with_inner._original_function (fun)": [
    "decorator.second_parameter_source_inlineable_decorator_with_inner._original_function.inner (fun)"
  ],
  "decorator.second_parameter_source_inlineable_decorator_with_inner._original_function.inner (fun)": [
    "_test_sink (fun)"
  ],
  "decorator.second_parameter_source_with_non_inlineable_decorator (fun)": [
    "_test_sink (fun)"
  ],
  "decorator.second_parameter_source_with_non_inlineable_decorator@decorated (fun)": [
    "decorator.discard_second_parameter_non_inlineable (fun)[formal(f, position=0)=decorator.second_parameter_source_with_non_inlineable_decorator (fun)]"
  ],
  "decorator.with_logging.inner (fun)": [ "_test_sink (fun)" ],
  "decorator.with_logging_args_kwargs.inner (fun)": [ "_test_sink (fun)" ],
  "decorator.with_logging_async.inner (fun)": [ "_test_sink (fun)" ],
  "decorator.with_logging_first_parameter.inner (fun)": [
    "_test_sink (fun)", "int.__eq__ (method)", "int.__ne__ (method)"
  ],
  "decorator.with_logging_helper_functions.after (fun)": [
    "_test_sink (fun)", "print (fun)"
  ],
  "decorator.with_logging_helper_functions.before (fun)": [ "print (fun)" ],
  "decorator.with_logging_helper_functions.inner (fun)": [
    "decorator.with_logging_helper_functions.after (fun)",
    "decorator.with_logging_helper_functions.before (fun)",
    "isinstance (fun)", "print (fun)"
  ],
  "decorator.with_logging_sink.inner (fun)": [ "_test_sink (fun)" ],
  "decorator.with_logging_source.inner (fun)": [
    "_test_source (fun)", "str.__add__ (method)"
  ],
  "decorator.with_named_logger._inner_decorator.inner (fun)": [
    "_test_sink (fun)", "print (fun)"
  ]
}