@generated
Call dependencies
$local_decorator_location?foo$__original_function (fun) -> [$local_decorator_location?foo?__original_function$__original_function (fun) __test_sink (fun)]
$local_decorator_location?foo$some_helper (fun) -> [__test_sink (fun) print (fun)]
$local_decorator_location?foo?__original_function$__original_function (fun) -> [__test_sink (fun)]
$local_decorator_location?with_logging$inner (fun) -> [$local_decorator_location?with_logging$some_helper (fun) __test_sink (fun)]
$local_decorator_location?with_logging$some_helper (fun) -> [__test_sink (fun) print (fun)]
$local_decorator_location?with_logging2$inner (fun) -> [__test_sink (fun)]
decorator_location.foo (fun) -> [$local_decorator_location?foo$__original_function (fun) $local_decorator_location?foo$some_helper (fun) __test_sink (fun)]
decorator_location.main (fun) -> [__test_source (fun) decorator_location.foo (fun)]
decorator_location.with_logging (fun) -> []
decorator_location.with_logging2 (fun) -> []
