@generated
Call dependencies
{
  "decorator_location.Foo.return_source (method)": [ "_test_source (fun)" ],
  "decorator_location.call_return_foo (fun)": [
    "_test_sink (fun)", "decorator_location.return_foo (fun)",
    "decorator_location.Foo.return_source (method)"
  ],
  "decorator_location.decorated_ignore_then_skip_decorator (fun)": [
    "_test_sink (fun)"
  ],
  "decorator_location.decorated_ignore_then_skip_decorator@decorated (fun)": [
    "decorator_location.skip_this_decorator (fun)[formal(f, position=0)=decorator_location.decorated_ignore_then_skip_decorator (fun)]"
  ],
  "decorator_location.decorated_ignore_this_decorator (fun)": [
    "_test_sink (fun)"
  ],
  "decorator_location.decorated_ignore_this_decorator_class (fun)": [
    "_test_sink (fun)"
  ],
  "decorator_location.decorated_ignore_this_decorator_factory (fun)": [
    "_test_sink (fun)"
  ],
  "decorator_location.decorated_logging2_skip_this_decorator (fun)": [
    "decorator_location.decorated_logging2_skip_this_decorator._inlined_with_logging2 (fun)",
    "decorator_location.decorated_logging2_skip_this_decorator._inlined_with_logging2 (fun)[local($local_decorator_location?decorated_logging2_skip_this_decorator$_original_function)=decorator_location.decorated_logging2_skip_this_decorator._original_function (fun)]"
  ],
  "decorator_location.decorated_logging2_skip_this_decorator._inlined_with_logging2 (fun)": [
    "_test_sink (fun)",
    "decorator_location.decorated_logging2_skip_this_decorator._original_function (fun)"
  ],
  "decorator_location.decorated_logging2_skip_this_decorator._inlined_with_logging2 (fun)[local($local_decorator_location?decorated_logging2_skip_this_decorator$_original_function)=decorator_location.decorated_logging2_skip_this_decorator._original_function (fun)]": [
    "_test_sink (fun)",
    "decorator_location.decorated_logging2_skip_this_decorator._original_function (fun)"
  ],
  "decorator_location.decorated_logging2_skip_this_decorator._original_function (fun)": [
    "_test_sink (fun)"
  ],
  "decorator_location.decorated_logging_ignore_this_decorator (fun)": [
    "decorator_location.decorated_logging_ignore_this_decorator._inlined_with_logging (fun)",
    "decorator_location.decorated_logging_ignore_this_decorator._inlined_with_logging (fun)[local($local_decorator_location?decorated_logging_ignore_this_decorator$_original_function)=decorator_location.decorated_logging_ignore_this_decorator._original_function (fun)]"
  ],
  "decorator_location.decorated_logging_ignore_this_decorator._inlined_with_logging (fun)": [
    "_test_sink (fun)",
    "decorator_location.decorated_logging_ignore_this_decorator._inlined_with_logging.some_helper (fun)",
    "decorator_location.decorated_logging_ignore_this_decorator._original_function (fun)"
  ],
  "decorator_location.decorated_logging_ignore_this_decorator._inlined_with_logging (fun)[local($local_decorator_location?decorated_logging_ignore_this_decorator$_original_function)=decorator_location.decorated_logging_ignore_this_decorator._original_function (fun)]": [
    "_test_sink (fun)",
    "decorator_location.decorated_logging_ignore_this_decorator._inlined_with_logging.some_helper (fun)",
    "decorator_location.decorated_logging_ignore_this_decorator._original_function (fun)"
  ],
  "decorator_location.decorated_logging_ignore_this_decorator._inlined_with_logging.some_helper (fun)": [
    "_test_sink (fun)", "print (fun)"
  ],
  "decorator_location.decorated_logging_ignore_this_decorator._original_function (fun)": [
    "_test_sink (fun)"
  ],
  "decorator_location.decorated_logging_logging2 (fun)": [
    "decorator_location.decorated_logging_logging2._inlined_with_logging (fun)",
    "decorator_location.decorated_logging_logging2._inlined_with_logging (fun)[local($local_decorator_location?decorated_logging_logging2$_inlined_with_logging2)=decorator_location.decorated_logging_logging2._inlined_with_logging2 (fun)[local($local_decorator_location?decorated_logging_logging2$_original_function)=decorator_location.decorated_logging_logging2._original_function (fun)]]"
  ],
  "decorator_location.decorated_logging_logging2._inlined_with_logging (fun)": [
    "_test_sink (fun)",
    "decorator_location.decorated_logging_logging2._inlined_with_logging.some_helper (fun)",
    "decorator_location.decorated_logging_logging2._inlined_with_logging2 (fun)"
  ],
  "decorator_location.decorated_logging_logging2._inlined_with_logging (fun)[local($local_decorator_location?decorated_logging_logging2$_inlined_with_logging2)=decorator_location.decorated_logging_logging2._inlined_with_logging2 (fun)[local($local_decorator_location?decorated_logging_logging2$_original_function)=decorator_location.decorated_logging_logging2._original_function (fun)]]": [
    "_test_sink (fun)",
    "decorator_location.decorated_logging_logging2._inlined_with_logging.some_helper (fun)",
    "decorator_location.decorated_logging_logging2._inlined_with_logging2 (fun)",
    "decorator_location.decorated_logging_logging2._inlined_with_logging2 (fun)[local($local_decorator_location?decorated_logging_logging2$_original_function)=decorator_location.decorated_logging_logging2._original_function (fun)]"
  ],
  "decorator_location.decorated_logging_logging2._inlined_with_logging.some_helper (fun)": [
    "_test_sink (fun)", "print (fun)"
  ],
  "decorator_location.decorated_logging_logging2._inlined_with_logging2 (fun)": [
    "_test_sink (fun)",
    "decorator_location.decorated_logging_logging2._original_function (fun)"
  ],
  "decorator_location.decorated_logging_logging2._inlined_with_logging2 (fun)[local($local_decorator_location?decorated_logging_logging2$_original_function)=decorator_location.decorated_logging_logging2._original_function (fun)]": [
    "_test_sink (fun)",
    "decorator_location.decorated_logging_logging2._original_function (fun)"
  ],
  "decorator_location.decorated_logging_logging2._original_function (fun)": [
    "_test_sink (fun)"
  ],
  "decorator_location.decorated_skip_this_decorator (fun)": [
    "_test_sink (fun)"
  ],
  "decorator_location.decorated_skip_this_decorator@decorated (fun)": [
    "decorator_location.skip_this_decorator (fun)[formal(f, position=0)=decorator_location.decorated_skip_this_decorator (fun)]"
  ],
  "decorator_location.handle_request (fun)": [
    "decorator_location.handle_request._inlined_pass_local_variable_to_x (fun)",
    "decorator_location.handle_request._inlined_pass_local_variable_to_x (fun)[local($local_decorator_location?handle_request$_original_function)=decorator_location.handle_request._original_function (fun)]"
  ],
  "decorator_location.handle_request._inlined_pass_local_variable_to_x (fun)": [
    "_test_sink (fun)",
    "decorator_location.handle_request._original_function (fun)"
  ],
  "decorator_location.handle_request._inlined_pass_local_variable_to_x (fun)[local($local_decorator_location?handle_request$_original_function)=decorator_location.handle_request._original_function (fun)]": [
    "_test_sink (fun)",
    "decorator_location.handle_request._original_function (fun)"
  ],
  "decorator_location.handle_request._original_function (fun)": [
    "_test_sink (fun)"
  ],
  "decorator_location.identity.inner@decorated (fun)": [
    "functools.wraps (fun)"
  ],
  "decorator_location.ignore_this_decorator_factory.decorator.inner (fun)": [
    "int.__add__ (method)"
  ],
  "decorator_location.main (fun)": [
    "_test_source (fun)", "decorator_location.call_return_foo (fun)",
    "decorator_location.decorated_ignore_this_decorator (fun)",
    "decorator_location.decorated_ignore_this_decorator_class (fun)",
    "decorator_location.decorated_ignore_this_decorator_factory (fun)",
    "decorator_location.decorated_logging2_skip_this_decorator (fun)",
    "decorator_location.decorated_logging_ignore_this_decorator (fun)",
    "decorator_location.decorated_logging_logging2 (fun)",
    "decorator_location.handle_request (fun)",
    "decorator_location.skip_this_decorator.inner (fun)[local($parameter$f)=decorator_location.decorated_ignore_then_skip_decorator (fun)]",
    "decorator_location.skip_this_decorator.inner (fun)[local($parameter$f)=decorator_location.decorated_skip_this_decorator (fun)]"
  ],
  "decorator_location.pass_local_variable_to_x.inner (fun)": [
    "_test_sink (fun)"
  ],
  "decorator_location.pass_local_variable_to_x.inner@decorated (fun)": [
    "functools.wraps (fun)"
  ],
  "decorator_location.return_foo (fun)": [
    "decorator_location.return_foo._inlined_identity (fun)",
    "decorator_location.return_foo._inlined_identity (fun)[local($local_decorator_location?return_foo$_original_function)=decorator_location.return_foo._original_function (fun)]"
  ],
  "decorator_location.return_foo._inlined_identity (fun)": [
    "decorator_location.return_foo._original_function (fun)"
  ],
  "decorator_location.return_foo._inlined_identity (fun)[local($local_decorator_location?return_foo$_original_function)=decorator_location.return_foo._original_function (fun)]": [
    "decorator_location.return_foo._original_function (fun)"
  ],
  "decorator_location.return_foo._original_function (fun)": [
    "object.__init__ (method)", "object.__new__ (method)"
  ],
  "decorator_location.skip_this_decorator.inner (fun)": [
    "_test_sink (fun)"
  ],
  "decorator_location.skip_this_decorator.inner (fun)[local($parameter$f)=decorator_location.decorated_ignore_then_skip_decorator (fun)]": [
    "_test_sink (fun)",
    "decorator_location.decorated_ignore_then_skip_decorator (fun)"
  ],
  "decorator_location.skip_this_decorator.inner (fun)[local($parameter$f)=decorator_location.decorated_skip_this_decorator (fun)]": [
    "_test_sink (fun)",
    "decorator_location.decorated_skip_this_decorator (fun)"
  ],
  "decorator_location.with_logging.inner (fun)": [
    "_test_sink (fun)", "decorator_location.with_logging.some_helper (fun)"
  ],
  "decorator_location.with_logging.some_helper (fun)": [
    "_test_sink (fun)", "print (fun)"
  ],
  "decorator_location.with_logging2.inner (fun)": [ "_test_sink (fun)" ]
}