@generated
Call dependencies
{
  "dictionary.Service.async_get_dict (method)": [
    "builtins.dict.get (method)",
    "dictionary.Service.async_get_many_dict (method)"
  ],
  "dictionary.Service.async_get_many_dict (method)": [
    "typing.Iterable.__iter__ (method)", "typing.Iterator.__next__ (method)",
    "typing.cast (fun)"
  ],
  "dictionary.Service.async_get_mapping (method)": [
    "dictionary.Service.async_get_many_dict (method)",
    "dictionary.to_map (fun)", "typing.Mapping.get (method)"
  ],
  "dictionary.SpecialSetitemDict.__setitem__ (method)": [
    "pysa._test_sink (fun)"
  ],
  "dictionary.analyze_getitem_index_backward (fun)": [
    "builtins.dict.__getitem__ (method)", "pysa._test_sink (fun)"
  ],
  "dictionary.analyze_getitem_index_issue (fun)": [
    "builtins.dict.__getitem__ (method)", "pysa._test_sink (fun)",
    "pysa._test_source (fun)"
  ],
  "dictionary.backward_weak_update (fun)": [
    "builtins.dict.__setitem__ (method)", "builtins.dict.keys (method)",
    "pysa._test_sink (fun)"
  ],
  "dictionary.backwards_field_assignment (fun)": [
    "builtins.dict.__setitem__ (method)"
  ],
  "dictionary.backwards_model_for_dictionary_comprehension (fun)": [
    "dictionary.sink_dictionary_through_keys (fun)"
  ],
  "dictionary.big_dict_update_arg (fun)": [
    "builtins.dict.__setitem__ (method)",
    "builtins.object.__init__ (method)", "builtins.range.__iter__ (method)",
    "builtins.range.__new__ (method)", "pysa._test_source (fun)",
    "typing.Iterator.__next__ (method)",
    "typing.MutableMapping.update (method)"
  ],
  "dictionary.copy_untainted_values_with_tainted_keys (fun)": [
    "builtins.dict.__getitem__ (method)", "builtins.dict.__iter__ (method)",
    "builtins.dict.__setitem__ (method)", "pysa._test_source (fun)",
    "typing.Iterator.__next__ (method)"
  ],
  "dictionary.dict_get_foo (fun)": [ "builtins.dict.get (method)" ],
  "dictionary.dict_get_foo_with_default (fun)": [
    "builtins.dict.get (method)"
  ],
  "dictionary.dict_getitem_mutate (fun)": [
    "builtins.dict.__getitem__ (method)",
    "builtins.dict.__setitem__ (method)",
    "builtins.object.__init__ (method)", "builtins.range.__iter__ (method)",
    "builtins.range.__new__ (method)", "builtins.str.__add__ (method)",
    "typing.Iterator.__next__ (method)"
  ],
  "dictionary.dict_only_key_of_parameter_sink (fun)": [
    "builtins.dict.__getitem__ (method)", "pysa._test_sink (fun)",
    "typing.MutableMapping.update (method)"
  ],
  "dictionary.dict_update_keys (fun)": [
    "builtins.dict.items (method)", "typing.ItemsView.__iter__ (method)",
    "typing.Iterator.__next__ (method)"
  ],
  "dictionary.dict_update_sinks_cycle (fun)": [
    "builtins.dict.__getitem__ (method)", "pysa._test_sink (fun)",
    "typing.MutableMapping.update (method)"
  ],
  "dictionary.dict_update_source_cycle (fun)": [
    "builtins.dict.__getitem__ (method)", "pysa._test_source (fun)",
    "typing.MutableMapping.update (method)"
  ],
  "dictionary.dict_update_with_expression_add_source (fun)": [
    "pysa._test_source (fun)", "typing.MutableMapping.update (method)"
  ],
  "dictionary.dict_update_with_expression_erase_source (fun)": [
    "pysa._test_source (fun)", "typing.MutableMapping.update (method)"
  ],
  "dictionary.dict_update_with_expression_tito (fun)": [
    "typing.MutableMapping.update (method)"
  ],
  "dictionary.dict_update_with_literal_flows_to_sink (fun)": [
    "builtins.dict.__getitem__ (method)", "pysa._test_sink (fun)",
    "typing.MutableMapping.update (method)"
  ],
  "dictionary.dict_update_with_literal_multiple (fun)": [
    "pysa._test_source (fun)", "typing.MutableMapping.update (method)"
  ],
  "dictionary.dict_update_with_literal_safe_source (fun)": [
    "pysa._test_source (fun)", "typing.MutableMapping.update (method)"
  ],
  "dictionary.dict_update_with_literal_source (fun)": [
    "pysa._test_source (fun)", "typing.MutableMapping.update (method)"
  ],
  "dictionary.dict_with_tainted_key_flows_to_sink (fun)": [
    "pysa._test_sink (fun)", "pysa._test_source (fun)"
  ],
  "dictionary.dict_with_tainted_key_flows_to_sink_via_setitem (fun)": [
    "builtins.dict.__setitem__ (method)", "pysa._test_sink (fun)",
    "pysa._test_source (fun)"
  ],
  "dictionary.dictionary_assign_to_index (fun)": [
    "builtins.dict.__setitem__ (method)", "pysa._test_source (fun)"
  ],
  "dictionary.dictionary_assignment_source (fun)": [
    "builtins.dict.__getitem__ (method)",
    "builtins.dict.__setitem__ (method)", "pysa._test_source (fun)"
  ],
  "dictionary.dictionary_bool_key (fun)": [
    "builtins.dict.__getitem__ (method)", "pysa._test_sink (fun)",
    "pysa._test_source (fun)"
  ],
  "dictionary.dictionary_entry_sink (fun)": [ "pysa._test_sink (fun)" ],
  "dictionary.dictionary_int_key (fun)": [
    "builtins.dict.__getitem__ (method)", "pysa._test_sink (fun)",
    "pysa._test_source (fun)"
  ],
  "dictionary.dictionary_keys_and_any_index_bug (fun)": [
    "builtins.dict.keys (method)", "dictionary.dict_update_keys (fun)",
    "pysa._test_sink (fun)"
  ],
  "dictionary.dictionary_nested_assignment_1 (fun)": [
    "builtins.dict.__getitem__ (method)", "pysa._test_source (fun)"
  ],
  "dictionary.dictionary_nested_assignment_2 (fun)": [
    "builtins.dict.__getitem__ (method)", "pysa._test_source (fun)"
  ],
  "dictionary.dictionary_nested_non_source_assignment (fun)": [
    "builtins.dict.__getitem__ (method)", "pysa._test_source (fun)"
  ],
  "dictionary.dictionary_non_source (fun)": [
    "builtins.dict.__getitem__ (method)",
    "builtins.dict.__setitem__ (method)", "pysa._test_source (fun)"
  ],
  "dictionary.dictionary_source (fun)": [ "pysa._test_source (fun)" ],
  "dictionary.dictionary_tito_any_index (fun)": [
    "builtins.object.__init__ (method)", "builtins.range.__iter__ (method)",
    "builtins.range.__new__ (method)", "typing.Iterator.__next__ (method)"
  ],
  "dictionary.dictionary_update_iterable (fun)": [
    "builtins.dict.__getitem__ (method)", "pysa._test_sink (fun)",
    "pysa._test_source (fun)", "typing.MutableMapping.update (method)"
  ],
  "dictionary.dictionary_update_keyword (fun)": [
    "builtins.dict.__getitem__ (method)", "pysa._test_sink (fun)",
    "pysa._test_source (fun)", "typing.MutableMapping.update (method)"
  ],
  "dictionary.flow_through_keywords (fun)": [
    "builtins.dict.__getitem__ (method)", "pysa._test_sink (fun)",
    "pysa._test_source (fun)"
  ],
  "dictionary.forward_comprehension_key_sink (fun)": [
    "builtins.list.__iter__ (method)", "pysa._test_sink (fun)",
    "typing.Iterator.__next__ (method)"
  ],
  "dictionary.forward_comprehension_key_source (fun)": [
    "builtins.list.__iter__ (method)", "pysa._test_source (fun)",
    "typing.Iterator.__next__ (method)"
  ],
  "dictionary.forward_comprehension_value_sink (fun)": [
    "builtins.list.__iter__ (method)", "pysa._test_sink (fun)",
    "typing.Iterator.__next__ (method)"
  ],
  "dictionary.forward_comprehension_value_source (fun)": [
    "builtins.list.__iter__ (method)", "pysa._test_source (fun)",
    "typing.Iterator.__next__ (method)"
  ],
  "dictionary.forward_weak_update (fun)": [
    "builtins.dict.__setitem__ (method)", "pysa._test_source (fun)"
  ],
  "dictionary.get_keys (fun)": [
    "builtins.dict.__iter__ (method)", "typing.Iterator.__next__ (method)"
  ],
  "dictionary.indirect_flow_from_source_to_global_dictionary (fun)": [
    "dictionary.update_dictionary_indirectly (fun)",
    "pysa._test_source (fun)"
  ],
  "dictionary.issue_in_keys (fun)": [
    "builtins.dict.__setitem__ (method)", "builtins.dict.keys (method)",
    "dictionary.backward_weak_update (fun)", "pysa._test_sink (fun)",
    "pysa._test_source (fun)"
  ],
  "dictionary.lists_of_dictionary_iteration_is_precise (fun)": [
    "builtins.dict.__getitem__ (method)", "builtins.list.__iter__ (method)",
    "pysa._test_sink (fun)", "pysa._test_source (fun)",
    "typing.Iterator.__next__ (method)"
  ],
  "dictionary.reassignment_removes_backwards_taint (fun)": [
    "pysa._test_sink (fun)"
  ],
  "dictionary.return_comprehension_with_tained_keys (fun)": [
    "builtins.dict.__iter__ (method)", "pysa._test_source (fun)",
    "typing.Iterator.__next__ (method)"
  ],
  "dictionary.return_comprehension_with_untainted_keys (fun)": [
    "builtins.dict.__iter__ (method)", "pysa._test_source (fun)",
    "typing.Iterator.__next__ (method)"
  ],
  "dictionary.setitem_models (fun)": [
    "builtins.dict.__init__ (method)", "builtins.dict.__new__ (method)",
    "builtins.dict.__setitem__ (method)",
    "dictionary.MyDict.__setitem__ (method)"
  ],
  "dictionary.sink_dictionary_through_keys (fun)": [
    "builtins.dict.__iter__ (method)", "pysa._test_sink (fun)",
    "typing.Iterator.__next__ (method)"
  ],
  "dictionary.taint_dict_keys (fun)": [
    "builtins.dict.keys (method)", "pysa._test_sink (fun)"
  ],
  "dictionary.taint_dict_keys_no_issue (fun)": [
    "dictionary.taint_dict_keys (fun)", "pysa._test_source (fun)"
  ],
  "dictionary.tainted_setitem (fun)": [
    "dictionary.SpecialSetitemDict.__setitem__ (method)",
    "pysa._test_source (fun)"
  ],
  "dictionary.test_dict_get_foo_tito (fun)": [
    "dictionary.dict_get_foo (fun)", "pysa._test_sink (fun)",
    "pysa._test_source (fun)"
  ],
  "dictionary.test_dict_get_source (fun)": [
    "builtins.dict.get (method)", "pysa._test_sink (fun)",
    "pysa._test_source (fun)"
  ],
  "dictionary.test_dict_getitem_mutate (fun)": [
    "dictionary.dict_getitem_mutate (fun)", "pysa._test_sink (fun)",
    "pysa._test_source (fun)"
  ],
  "dictionary.test_dict_multiple_targets (fun)": [
    "builtins.dict.__getitem__ (method)", "pysa._test_sink (fun)",
    "pysa._test_source (fun)"
  ],
  "dictionary.test_dict_sanitize_get (fun)": [
    "builtins.dict.get (method)", "pysa._test_sink (fun)",
    "pysa._test_source (fun)"
  ],
  "dictionary.test_dict_sanitize_getitem (fun)": [
    "builtins.dict.__getitem__ (method)", "pysa._test_sink (fun)",
    "pysa._test_source (fun)"
  ],
  "dictionary.test_index_from_tito (fun)": [
    "dictionary.tito_with_index (fun)", "pysa._test_sink (fun)",
    "pysa._test_source (fun)"
  ],
  "dictionary.test_items (fun)": [
    "builtins.dict.items (method)", "pysa._test_sink (fun)",
    "pysa._test_source (fun)", "typing.ItemsView.__iter__ (method)",
    "typing.Iterator.__next__ (method)"
  ],
  "dictionary.test_items_backward_keys (fun)": [
    "builtins.dict.items (method)", "pysa._test_sink (fun)",
    "typing.ItemsView.__iter__ (method)", "typing.Iterator.__next__ (method)"
  ],
  "dictionary.test_items_backward_values (fun)": [
    "builtins.dict.items (method)", "pysa._test_sink (fun)",
    "typing.ItemsView.__iter__ (method)", "typing.Iterator.__next__ (method)"
  ],
  "dictionary.test_keys_and_values (fun)": [
    "builtins.dict.keys (method)", "builtins.dict.values (method)",
    "builtins.tuple.__getitem__ (method)", "pysa._test_sink (fun)",
    "pysa._test_source (fun)", "typing.Iterator.__next__ (method)",
    "typing.KeysView.__iter__ (method)",
    "typing.ValuesView.__iter__ (method)"
  ],
  "dictionary.test_mapping_sanitize_get (fun)": [
    "pysa._test_sink (fun)", "pysa._test_source (fun)",
    "typing.Mapping.get (method)"
  ],
  "dictionary.test_mapping_sanitize_getitem (fun)": [
    "pysa._test_sink (fun)", "pysa._test_source (fun)",
    "typing.Mapping.__getitem__ (method)"
  ],
  "dictionary.test_service_with_dict (fun)": [
    "builtins.object.__init__ (method)", "builtins.object.__new__ (method)",
    "dictionary.Service.async_get_dict (method)", "pysa._test_sink (fun)",
    "pysa._test_source (fun)"
  ],
  "dictionary.test_service_with_mapping (fun)": [
    "builtins.object.__init__ (method)", "builtins.object.__new__ (method)",
    "dictionary.Service.async_get_mapping (method)", "pysa._test_sink (fun)",
    "pysa._test_source (fun)"
  ],
  "dictionary.test_type_comments (fun)": [
    "builtins.dict.__setitem__ (method)"
  ],
  "dictionary.test_with_issue_in_dict_comprehension (fun)": [
    "builtins.list.__iter__ (method)", "pysa._test_sink (fun)",
    "pysa._test_source (fun)", "typing.Iterator.__next__ (method)"
  ],
  "dictionary.test_with_issue_in_dict_items_comprehension (fun)": [
    "builtins.dict.items (method)", "pysa._test_source (fun)",
    "typing.ItemsView.__iter__ (method)", "typing.Iterator.__next__ (method)"
  ],
  "dictionary.tito_with_index (fun)": [
    "builtins.dict.__getitem__ (method)"
  ],
  "dictionary.update_dictionary_indirectly (fun)": [
    "typing.MutableMapping.update (method)"
  ],
  "dictionary.update_parameter (fun)": [ "pysa._test_source (fun)" ],
  "dictionary.update_tainted_dictionary (fun)": [
    "pysa._test_source (fun)", "typing.MutableMapping.update (method)"
  ],
  "dictionary.update_tainted_dictionary_sink (fun)": [
    "pysa._test_sink (fun)", "typing.MutableMapping.update (method)"
  ],
  "dictionary.walrus_operator (fun)": [
    "builtins.dict.__setitem__ (method)", "pysa._test_source (fun)"
  ]
}