@generated
Call dependencies
{
  "entrypoint.$toplevel (fun)": [
    "entrypoint.main (fun)", "str.__eq__ (method)", "str.__ne__ (method)"
  ],
  "entrypoint.MyClass.method_entrypoint_with_decorator (method)": [
    "list.append (method)"
  ],
  "entrypoint.MyClass.method_entrypoint_with_decorator@decorated (method)": [
    "entrypoint.MyEntrypoint (fun)[formal(f, position=0)=entrypoint.MyClass.method_entrypoint_with_decorator (method)]"
  ],
  "entrypoint.MyClass.some_entrypoint_function (method)": [
    "list.append (method)"
  ],
  "entrypoint.MyEntrypoint (fun)[formal(f, position=0)=entrypoint.MyClass.method_entrypoint_with_decorator (method)]": [
    "entrypoint.MyClass.method_entrypoint_with_decorator (method)"
  ],
  "entrypoint.MyEntrypoint (fun)[formal(f, position=0)=entrypoint.function_entrypoint_with_decorator (fun)]": [
    "entrypoint.function_entrypoint_with_decorator (fun)"
  ],
  "entrypoint.entrypoint_into_lambda (fun)": [
    "entrypoint.entrypoint_into_lambda.lambda_entrypoint_with_decorator (fun)"
  ],
  "entrypoint.entrypoint_into_lambda.lambda_entrypoint_with_decorator (fun)": [
    "list.append (method)"
  ],
  "entrypoint.entrypoint_into_lambda.lambda_entrypoint_with_decorator@decorated (fun)": [
    "entrypoint.MyEntrypoint (fun)"
  ],
  "entrypoint.function_entrypoint_with_decorator (fun)": [
    "list.append (method)"
  ],
  "entrypoint.function_entrypoint_with_decorator@decorated (fun)": [
    "entrypoint.MyEntrypoint (fun)[formal(f, position=0)=entrypoint.function_entrypoint_with_decorator (fun)]"
  ],
  "entrypoint.get_these (fun)": [
    "entrypoint.immediate_examples (fun)",
    "entrypoint.leak_globals_by_passing_in (fun)",
    "entrypoint.leak_globals_by_transitive_call (fun)",
    "entrypoint.nested_run (fun)"
  ],
  "entrypoint.immediate_examples (fun)": [ "list.append (method)" ],
  "entrypoint.leak_globals_by_passing_in (fun)": [
    "entrypoint.transitive_call_with_globals_passed_in (fun)"
  ],
  "entrypoint.leak_globals_by_transitive_call (fun)": [
    "entrypoint.transitive_call_accessing_globals (fun)"
  ],
  "entrypoint.main (fun)": [
    "entrypoint.MyClass.some_entrypoint_function (method)",
    "entrypoint.get_these (fun)",
    "entrypoint.this_one_shouldnt_be_found (fun)",
    "object.__init__ (method)", "object.__new__ (method)"
  ],
  "entrypoint.nested_run (fun)": [
    "entrypoint.nested_run.do_the_thing (fun)"
  ],
  "entrypoint.nested_run.do_the_thing (fun)": [ "list.append (method)" ],
  "entrypoint.this_one_shouldnt_be_found (fun)": [ "list.append (method)" ],
  "entrypoint.transitive_call_accessing_globals (fun)": [
    "list.append (method)"
  ],
  "entrypoint.transitive_call_with_globals_passed_in (fun)": [
    "list.append (method)"
  ]
}