@generated
Call dependencies
{
  "exception_test.none_throws (fun)": [
    "builtins.BaseException.__init__ (method)",
    "builtins.BaseException.__new__ (method)"
  ],
  "exception_test.test_before_try_to_finally (fun)": [
    "exception_test.none_throws (fun)", "pysa._test_sink (fun)",
    "pysa._test_source (fun)"
  ],
  "exception_test.test_caught_exception (fun)": [
    "builtins.BaseException.__str__ (method)", "builtins.isinstance (fun)",
    "builtins.object.__init__ (method)", "builtins.str.__new__ (method)"
  ],
  "exception_test.test_constructed_exception (fun)": [
    "builtins.BaseException.__init__ (method)",
    "builtins.BaseException.__new__ (method)",
    "builtins.BaseException.__str__ (method)",
    "builtins.object.__init__ (method)", "builtins.str.__new__ (method)"
  ],
  "exception_test.test_except_to_finally (fun)": [
    "exception_test.none_throws (fun)", "pysa._test_sink (fun)",
    "pysa._test_source (fun)"
  ],
  "exception_test.test_parameter_flow (fun)": [
    "builtins.BaseException.__str__ (method)",
    "builtins.object.__init__ (method)", "builtins.str.__new__ (method)"
  ],
  "exception_test.test_return_finally (fun)": [
    "builtins.print (fun)", "pysa._test_source (fun)"
  ],
  "exception_test.test_return_overrides_finally (fun)": [
    "pysa._test_source (fun)"
  ],
  "exception_test.test_return_twice_finally (fun)": [
    "pysa._test_source (fun)"
  ],
  "exception_test.test_sink_in_finally (fun)": [
    "exception_test.none_throws (fun)", "pysa._test_sink (fun)"
  ],
  "exception_test.test_within_try_to_finally (fun)": [
    "exception_test.none_throws (fun)", "pysa._test_sink (fun)",
    "pysa._test_source (fun)"
  ]
}