@generated
Call dependencies
{
  "first_index.alternate_fields (fun)": [
    "dict.__getitem__ (method)", "int.__gt__ (method)",
    "int.__le__ (method)", "pysa._test_sink (fun)", "pysa._test_source (fun)"
  ],
  "first_index.local_fields (fun)": [
    "first_index.alternate_fields (fun)", "int.__gt__ (method)",
    "int.__le__ (method)"
  ],
  "first_index.local_fields_hop (fun)": [
    "first_index.local_fields (fun)", "int.__gt__ (method)",
    "int.__le__ (method)"
  ]
}