@generated
Call dependencies
{
  "format.issue_in_format (fun)": [
    "object.__repr__ (method)", "pysa._test_sink (fun)",
    "pysa._test_source (fun)"
  ],
  "format.issue_in_format_specifier (fun)": [
    "object.__repr__ (method)", "pysa._test_sink (fun)",
    "pysa._test_source (fun)", "str.__str__ (method)"
  ],
  "format.sink_in_format (fun)": [
    "object.__repr__ (method)", "pysa._test_sink (fun)"
  ],
  "format.sink_in_format_specifier (fun)": [
    "object.__repr__ (method)", "pysa._test_sink (fun)",
    "str.__str__ (method)"
  ],
  "format.sink_via_format (fun)": [ "pysa._test_sink (fun)" ],
  "format.source_in_format (fun)": [ "pysa._test_source (fun)" ],
  "format.source_in_format_specifier (fun)": [
    "pysa._test_source (fun)", "str.__str__ (method)"
  ],
  "format.source_via_format (fun)": [ "pysa._test_source (fun)" ]
}