@generated
Call dependencies
format.$toplevel (fun) -> []
format.issue_in_format (fun) -> [_test_sink (fun) _test_source (fun) object::__repr__ (method)]
format.sink_in_format (fun) -> [_test_sink (fun) object::__repr__ (method)]
format.sink_via_format (fun) -> [_test_sink (fun)]
format.source_in_format (fun) -> [_test_source (fun)]
format.source_via_format (fun) -> [_test_source (fun)]
format.tito_via_format (fun) -> []
