@generated
Call dependencies
{
  "format.issue_in_format (fun)": [
    "_test_sink (fun)", "_test_source (fun)", "object.__repr__ (method)"
  ],
  "format.issue_in_format_specifier (fun)": [
    "_test_sink (fun)", "_test_source (fun)", "object.__repr__ (method)",
    "str.__str__ (method)"
  ],
  "format.sink_in_format (fun)": [
    "_test_sink (fun)", "object.__repr__ (method)"
  ],
  "format.sink_in_format_specifier (fun)": [
    "_test_sink (fun)", "object.__repr__ (method)", "str.__str__ (method)"
  ],
  "format.sink_via_format (fun)": [ "_test_sink (fun)" ],
  "format.source_in_format (fun)": [ "_test_source (fun)" ],
  "format.source_in_format_specifier (fun)": [
    "_test_source (fun)", "str.__str__ (method)"
  ],
  "format.source_via_format (fun)": [ "_test_source (fun)" ]
}