@generated
Call dependencies
{
  "global.$toplevel (fun)": [
    "global.create_global_source (fun)", "object.__init__ (method)",
    "object.__new__ (method)", "pysa._test_source (fun)"
  ],
  "global.create_global_source (fun)": [ "pysa._test_source (fun)" ],
  "global.obj1_flow (fun)": [
    "global.obj1_sink (fun)", "global.obj1_source (fun)"
  ],
  "global.obj1_no_flow (fun)": [
    "global.obj1_sink (fun)", "global.obj1_source (fun)"
  ],
  "global.obj1_sink (fun)": [ "pysa._test_sink (fun)" ],
  "global.obj1_source (fun)": [ "pysa._test_source (fun)" ],
  "global.obj2_sink (fun)": [ "pysa._test_sink (fun)" ],
  "global.obj3_flow (fun)": [
    "global.obj3_return (fun)", "global.obj3_set (fun)",
    "pysa._test_sink (fun)", "pysa._test_source (fun)"
  ],
  "global.obj4_flow (fun)": [ "pysa._test_sink (fun)" ],
  "global.obj6_flow (fun)": [
    "global.obj6_sink (fun)", "global.obj6_source (fun)"
  ],
  "global.obj6_sink (fun)": [ "pysa._test_sink (fun)" ],
  "global.obj6_source (fun)": [ "pysa._test_source (fun)" ],
  "global.obj7_flow (fun)": [
    "global.obj7_sink (fun)", "global.obj7_source (fun)"
  ],
  "global.obj7_sink (fun)": [ "pysa._test_sink (fun)" ],
  "global.obj7_source (fun)": [ "pysa._test_source (fun)" ],
  "global.obj8_flow (fun)": [
    "global.obj8_return (fun)", "global.obj8_set (fun)",
    "pysa._test_sink (fun)", "pysa._test_source (fun)"
  ]
}