@generated
Call dependencies
global.$toplevel (fun) -> [_test_source (fun) object::__init__ (method) object::__new__ (method)]
global.obj1_flow (fun) -> [global.obj1_sink (fun) global.obj1_source (fun)]
global.obj1_no_flow (fun) -> [global.obj1_sink (fun) global.obj1_source (fun)]
global.obj1_sink (fun) -> [_test_sink (fun)]
global.obj1_source (fun) -> [_test_source (fun)]
global.obj2_sink (fun) -> [_test_sink (fun)]
global.obj3_flow (fun) -> [_test_sink (fun) _test_source (fun) global.obj3_return (fun) global.obj3_set (fun)]
global.obj3_return (fun) -> []
global.obj3_set (fun) -> []
global.obj4_flow (fun) -> [_test_sink (fun)]
