@generated
Call dependencies
{
  "higher_order_functions.$toplevel (fun)": [
    "higher_order_functions.test_duplicate_issues_in_different_parameterized_callables (fun)[formal(f, position=0)=builtins.print (fun)]",
    "pysa._test_source (fun)"
  ],
  "higher_order_functions.C.method_to_sink (method)": [
    "pysa._test_sink (fun)"
  ],
  "higher_order_functions.C.self_to_sink (method)": [
    "pysa._test_sink (fun)"
  ],
  "higher_order_functions.CallableSource.__call__ (method)": [
    "pysa._test_source (fun)"
  ],
  "higher_order_functions.apply (fun)[formal(f, position=0)=higher_order_functions.has_tito (fun)]": [
    "higher_order_functions.has_tito (fun)"
  ],
  "higher_order_functions.apply (fun)[formal(f, position=0)=higher_order_functions.test_duplicate_issues_in_different_parameterized_callables.sink_wrapper2 (fun)]": [
    "higher_order_functions.test_duplicate_issues_in_different_parameterized_callables.sink_wrapper2 (fun)"
  ],
  "higher_order_functions.apply (fun)[formal(f, position=0)=pysa._test_sink (fun)]": [
    "pysa._test_sink (fun)"
  ],
  "higher_order_functions.apply (fun)[formal(f, position=0)=pysa._test_source (fun)]": [
    "pysa._test_source (fun)"
  ],
  "higher_order_functions.apply_without_return (fun)[formal(f, position=0)=pysa._test_sink (fun)]": [
    "pysa._test_sink (fun)"
  ],
  "higher_order_functions.callable_class (fun)": [
    "builtins.object.__new__ (method)",
    "higher_order_functions.Callable.__call__ (method)",
    "higher_order_functions.Callable.__init__ (method)",
    "pysa._test_sink (fun)", "pysa._test_source (fun)"
  ],
  "higher_order_functions.conditional_apply (fun)[formal(f, position=0)=higher_order_functions.safe (fun), formal(g, position=1)=pysa._test_sink (fun)]": [
    "higher_order_functions.safe (fun)", "pysa._test_sink (fun)"
  ],
  "higher_order_functions.conditional_apply (fun)[formal(f, position=0)=higher_order_functions.safe (fun), formal(g, position=1)=pysa._test_source (fun)]": [
    "higher_order_functions.safe (fun)", "pysa._test_source (fun)"
  ],
  "higher_order_functions.conditional_apply (fun)[formal(f, position=0)=pysa._test_sink (fun), formal(g, position=1)=higher_order_functions.safe (fun)]": [
    "higher_order_functions.safe (fun)", "pysa._test_sink (fun)"
  ],
  "higher_order_functions.conditional_apply (fun)[formal(f, position=0)=pysa._test_source (fun), formal(g, position=1)=higher_order_functions.safe (fun)]": [
    "higher_order_functions.safe (fun)", "pysa._test_source (fun)"
  ],
  "higher_order_functions.goes_to_sink (fun)": [ "pysa._test_sink (fun)" ],
  "higher_order_functions.higher_order_function (fun)[formal(f, position=0)=higher_order_functions.C.method_to_sink (method)]": [
    "higher_order_functions.C.method_to_sink (method)"
  ],
  "higher_order_functions.higher_order_function (fun)[formal(f, position=0)=higher_order_functions.C.self_to_sink (method)]": [
    "higher_order_functions.C.self_to_sink (method)"
  ],
  "higher_order_functions.higher_order_function (fun)[formal(f, position=0)=higher_order_functions.goes_to_sink (fun)]": [
    "higher_order_functions.goes_to_sink (fun)"
  ],
  "higher_order_functions.higher_order_function (fun)[formal(f, position=0)=higher_order_functions.has_tito (fun)]": [
    "higher_order_functions.has_tito (fun)"
  ],
  "higher_order_functions.higher_order_function_and_sink (fun)": [
    "pysa._test_sink (fun)"
  ],
  "higher_order_functions.higher_order_function_and_sink (fun)[formal(f, position=0)=higher_order_functions.goes_to_sink (fun)]": [
    "higher_order_functions.goes_to_sink (fun)", "pysa._test_sink (fun)"
  ],
  "higher_order_functions.higher_order_method (fun)": [
    "higher_order_functions.higher_order_function (fun)[formal(f, position=0)=higher_order_functions.C.method_to_sink (method)]"
  ],
  "higher_order_functions.sink_after_apply (fun)": [
    "pysa._test_sink (fun)"
  ],
  "higher_order_functions.sink_after_apply (fun)[formal(f, position=0)=pysa._test_source (fun)]": [
    "pysa._test_sink (fun)", "pysa._test_source (fun)"
  ],
  "higher_order_functions.sink_args (fun)": [
    "builtins.tuple.__iter__ (method)", "pysa._test_sink (fun)",
    "typing.Iterator.__next__ (method)"
  ],
  "higher_order_functions.source_through_tito (fun)": [
    "higher_order_functions.apply (fun)[formal(f, position=0)=higher_order_functions.has_tito (fun)]",
    "pysa._test_source (fun)"
  ],
  "higher_order_functions.test_apply_source (fun)": [
    "higher_order_functions.apply (fun)[formal(f, position=0)=pysa._test_source (fun)]"
  ],
  "higher_order_functions.test_apply_tito (fun)": [
    "higher_order_functions.apply (fun)[formal(f, position=0)=higher_order_functions.has_tito (fun)]"
  ],
  "higher_order_functions.test_apply_without_return (fun)": [
    "higher_order_functions.apply_without_return (fun)",
    "higher_order_functions.apply_without_return (fun)[formal(f, position=0)=pysa._test_sink (fun)]",
    "pysa._test_source (fun)"
  ],
  "higher_order_functions.test_callable_class_to_obscure (fun)": [
    "builtins.object.__new__ (method)",
    "higher_order_functions.CallableSource.__call__ (method)",
    "higher_order_functions.CallableSource.__init__ (method)",
    "higher_order_functions.test_callable_class_to_obscure.obscure_tito (fun)"
  ],
  "higher_order_functions.test_callable_class_to_perfect_tito (fun)": [
    "builtins.object.__new__ (method)",
    "higher_order_functions.CallableSource.__init__ (method)",
    "higher_order_functions.test_callable_class_to_perfect_tito.perfect_tito (fun)[formal(x, position=0)=higher_order_functions.CallableSource.__call__ (method)]"
  ],
  "higher_order_functions.test_callable_default_value (fun)": [
    "pysa._test_sink (fun)", "pysa._test_source (fun)"
  ],
  "higher_order_functions.test_conditional_apply_backward (fun)": [
    "higher_order_functions.conditional_apply (fun)[formal(f, position=0)=higher_order_functions.safe (fun), formal(g, position=1)=pysa._test_sink (fun)]",
    "higher_order_functions.conditional_apply (fun)[formal(f, position=0)=pysa._test_sink (fun), formal(g, position=1)=higher_order_functions.safe (fun)]"
  ],
  "higher_order_functions.test_conditional_apply_forward (fun)": [
    "higher_order_functions.conditional_apply (fun)[formal(f, position=0)=higher_order_functions.safe (fun), formal(g, position=1)=pysa._test_source (fun)]",
    "higher_order_functions.conditional_apply (fun)[formal(f, position=0)=pysa._test_source (fun), formal(g, position=1)=higher_order_functions.safe (fun)]",
    "pysa._test_sink (fun)"
  ],
  "higher_order_functions.test_duplicate_issues_in_different_parameterized_callables (fun)": [
    "higher_order_functions.apply (fun)[formal(f, position=0)=higher_order_functions.test_duplicate_issues_in_different_parameterized_callables.sink_wrapper2 (fun)]",
    "higher_order_functions.apply (fun)[formal(f, position=0)=pysa._test_sink (fun)]",
    "higher_order_functions.test_duplicate_issues_in_different_parameterized_callables.sink_wrapper (fun)[formal(f, position=0)=higher_order_functions.test_duplicate_issues_in_different_parameterized_callables.bar (fun)]",
    "higher_order_functions.test_duplicate_issues_in_different_parameterized_callables.sink_wrapper (fun)[formal(f, position=0)=higher_order_functions.test_duplicate_issues_in_different_parameterized_callables.foo (fun)]",
    "pysa._test_source (fun)"
  ],
  "higher_order_functions.test_duplicate_issues_in_different_parameterized_callables (fun)[formal(f, position=0)=builtins.print (fun)]": [
    "higher_order_functions.apply (fun)[formal(f, position=0)=higher_order_functions.test_duplicate_issues_in_different_parameterized_callables.sink_wrapper2 (fun)]",
    "higher_order_functions.apply (fun)[formal(f, position=0)=pysa._test_sink (fun)]",
    "higher_order_functions.test_duplicate_issues_in_different_parameterized_callables.sink_wrapper (fun)[formal(f, position=0)=higher_order_functions.test_duplicate_issues_in_different_parameterized_callables.bar (fun)]",
    "higher_order_functions.test_duplicate_issues_in_different_parameterized_callables.sink_wrapper (fun)[formal(f, position=0)=higher_order_functions.test_duplicate_issues_in_different_parameterized_callables.foo (fun)]",
    "pysa._test_source (fun)"
  ],
  "higher_order_functions.test_duplicate_issues_in_different_parameterized_callables.sink_wrapper (fun)": [
    "pysa._test_sink (fun)"
  ],
  "higher_order_functions.test_duplicate_issues_in_different_parameterized_callables.sink_wrapper (fun)[formal(f, position=0)=higher_order_functions.test_duplicate_issues_in_different_parameterized_callables.bar (fun)]": [
    "pysa._test_sink (fun)"
  ],
  "higher_order_functions.test_duplicate_issues_in_different_parameterized_callables.sink_wrapper (fun)[formal(f, position=0)=higher_order_functions.test_duplicate_issues_in_different_parameterized_callables.foo (fun)]": [
    "pysa._test_sink (fun)"
  ],
  "higher_order_functions.test_duplicate_issues_in_different_parameterized_callables.sink_wrapper2 (fun)": [
    "pysa._test_sink (fun)"
  ],
  "higher_order_functions.test_higher_order_function (fun)": [
    "higher_order_functions.higher_order_function (fun)[formal(f, position=0)=higher_order_functions.goes_to_sink (fun)]",
    "pysa._test_source (fun)"
  ],
  "higher_order_functions.test_higher_order_function_and_sink (fun)": [
    "higher_order_functions.higher_order_function_and_sink (fun)[formal(f, position=0)=higher_order_functions.goes_to_sink (fun)]",
    "pysa._test_source (fun)"
  ],
  "higher_order_functions.test_higher_order_method (fun)": [
    "builtins.object.__init__ (method)", "builtins.object.__new__ (method)",
    "higher_order_functions.higher_order_method (fun)",
    "pysa._test_source (fun)"
  ],
  "higher_order_functions.test_higher_order_method_self (fun)": [
    "higher_order_functions.higher_order_function (fun)[formal(f, position=0)=higher_order_functions.C.self_to_sink (method)]",
    "pysa._test_source (fun)"
  ],
  "higher_order_functions.test_higher_order_tito (fun)": [
    "higher_order_functions.higher_order_function (fun)[formal(f, position=0)=higher_order_functions.has_tito (fun)]"
  ],
  "higher_order_functions.test_location (fun)": [
    "higher_order_functions.Callable.__call__ (method)",
    "higher_order_functions.sink_args (fun)"
  ],
  "higher_order_functions.test_parameterized_target_in_issue_handle (fun)": [
    "higher_order_functions.sink_after_apply (fun)[formal(f, position=0)=pysa._test_source (fun)]"
  ]
}