@generated
Call dependencies
http_request.$toplevel (fun) -> []
http_request.request_get_flows_to_sink (fun) -> [_test_sink (fun) django.http.request.HttpRequest.GET (object)]
http_request.test_hop_is_cut_off (fun) -> [_test_source (fun) django.http.request.HttpRequest.GET (object) http_request.request_get_flows_to_sink (fun)]
http_request.test_trace_has_no_tito (fun) -> [_test_sink (fun) _test_source (fun) django.http.request.HttpRequest.GET (object)]
http_request.test_untainted_assign (fun) -> [_test_sink (fun) django.http.request.HttpRequest.GET (object)]
