@generated
Call dependencies
{
  "implicit_sinks.conditional_literal_sink (fun)": [
    "implicit_sinks.format_wrapper (fun)", "pysa._test_source (fun)"
  ],
  "implicit_sinks.implicit_sink_before_parameter (fun)": [
    "str.format (method)"
  ],
  "implicit_sinks.implicit_sink_before_source (fun)": [
    "pysa._test_source (fun)", "str.format (method)"
  ],
  "implicit_sinks.inline_issue_dot_format (fun)": [
    "pysa._test_source (fun)", "str.format (method)"
  ],
  "implicit_sinks.inline_issue_format_string (fun)": [
    "pysa._test_source (fun)"
  ],
  "implicit_sinks.inline_issue_format_string_proper_tito (fun)": [
    "pysa._test_source (fun)", "str.__str__ (method)"
  ],
  "implicit_sinks.inline_issue_lhs_add_literal (fun)": [
    "pysa._test_source (fun)"
  ],
  "implicit_sinks.inline_issue_percent_format (fun)": [
    "pysa._test_source (fun)", "str.__mod__ (method)"
  ],
  "implicit_sinks.inline_issue_rhs_add_literal (fun)": [
    "pysa._test_source (fun)", "str.__add__ (method)"
  ],
  "implicit_sinks.propagate_sink_add_global (fun)": [
    "str.__add__ (method)"
  ],
  "implicit_sinks.propagate_sink_dot_format (fun)": [ "str.format (method)" ],
  "implicit_sinks.propagate_sink_percent_format (fun)": [
    "str.__mod__ (method)"
  ],
  "implicit_sinks.propagate_sink_rhs_add_literal (fun)": [
    "str.__add__ (method)"
  ],
  "implicit_sinks.string_literal_arguments_issue (fun)": [
    "implicit_sinks.string_literal_arguments_sink (fun)",
    "pysa._test_source (fun)"
  ],
  "implicit_sinks.string_literal_arguments_sink (fun)": [
    "float.__gt__ (method)", "float.__le__ (method)",
    "pysa._test_source (fun)", "random.random (fun)", "str.__mod__ (method)",
    "str.format (method)"
  ]
}