@generated
Call dependencies
{
  "kwargs_and_args.args_sink (fun)": [
    "pysa._test_sink (fun)", "tuple.__getitem__ (method)"
  ],
  "kwargs_and_args.async_distillery_render (fun)": [
    "dict.__setitem__ (method)",
    "kwargs_and_args.async_render_to_response (fun)",
    "pysa._test_source (fun)", "typing.MutableMapping.pop (method)"
  ],
  "kwargs_and_args.async_render_to_response (fun)": [
    "pysa._test_sink (fun)"
  ]
}