@generated
Call dependencies
{
  "kwargs_and_args.args_sink (fun)": [
    "builtins.tuple.__getitem__ (method)", "pysa._test_sink (fun)"
  ],
  "kwargs_and_args.async_distillery_render (fun)": [
    "builtins.dict.__setitem__ (method)", "builtins.dict.pop (method)",
    "kwargs_and_args.async_render_to_response (fun)",
    "pysa._test_source (fun)"
  ],
  "kwargs_and_args.async_render_to_response (fun)": [
    "pysa._test_sink (fun)"
  ]
}