@generated
Call dependencies
{
  "lambda.lambda_sink (fun)": [
    "list.__init__ (method)", "map.__init__ (method)",
    "object.__new__ (method)", "pysa._test_sink (fun)"
  ],
  "lambda.lambda_source (fun)": [
    "list.__init__ (method)", "map.__init__ (method)",
    "object.__new__ (method)", "pysa._test_source (fun)"
  ],
  "lambda.test_filter_lambda (fun)": [
    "filter.__new__ (method)", "list.__getitem__ (method)",
    "list.__init__ (method)", "object.__init__ (method)",
    "object.__new__ (method)", "pysa._test_sink (fun)",
    "pysa._test_source (fun)"
  ],
  "lambda.test_lambda_sink (fun)": [
    "lambda.lambda_sink (fun)", "pysa._test_source (fun)"
  ],
  "lambda.test_lambda_source (fun)": [
    "lambda.lambda_source (fun)", "pysa._test_sink (fun)"
  ],
  "lambda.test_map_lambda (fun)": [
    "dict.__getitem__ (method)", "list.__getitem__ (method)",
    "list.__init__ (method)", "map.__init__ (method)",
    "object.__new__ (method)", "pysa._test_sink (fun)",
    "pysa._test_source (fun)"
  ]
}