@generated
Call dependencies
list.create_zipped_source_with_all_tainted (fun) -> [_test_source (fun)]
list.$toplevel (fun) -> []
list.create_zipped_source (fun) -> [_test_source (fun)]
list.push_pop_no_taint (fun) -> [_test_source (fun) list::append (method)]
list.push_pop_taint (fun) -> [_test_source (fun) list::append (method)]
list.zipped_element_not_flowing_to_sink (fun) -> [_test_sink (fun)]
list.zipped_element_to_sink (fun) -> [_test_sink (fun)]
list.zipped_source_access_path (fun) -> [_test_source (fun) list::__getitem__ (method) list::__init__ (method) object::__new__ (method)]
list.Woot::$class_toplevel (method) -> []
