@generated
Call dependencies
{
  "long_access_path_taint.C.__init__ (method)": [
    "builtins.dict.get (method)"
  ],
  "long_access_path_taint.C.async_create (method)": [
    "builtins.object.__init__ (method)", "builtins.object.__new__ (method)",
    "builtins.object.__repr__ (method)", "builtins.str.__eq__ (method)",
    "builtins.str.__new__ (method)",
    "long_access_path_taint.C.__init__ (method)"
  ],
  "long_access_path_taint.test (fun)": [
    "long_access_path_taint.C.async_create (method)",
    "pysa._test_sink (fun)", "pysa._test_source (fun)"
  ]
}