@generated
Call dependencies
{
  "match.test_match_class_pattern (fun)": [
    "_test_sink (fun)", "_test_source (fun)", "getattr (fun)",
    "isinstance (fun)", "match.MyClass.__init__ (method)",
    "object.__new__ (method)", "str.__eq__ (method)", "str.__ne__ (method)",
    "tuple.__getitem__ (method)"
  ],
  "match.test_match_equality (fun)": [
    "_test_sink (fun)", "_test_source (fun)"
  ],
  "match.test_match_list_pattern (fun)": [
    "_test_sink (fun)", "_test_source (fun)", "isinstance (fun)",
    "list.__getitem__ (method)", "list.__init__ (method)",
    "object.__eq__ (method)", "object.__ne__ (method)",
    "object.__new__ (method)", "slice.__init__ (method)"
  ],
  "match.test_match_list_pattern_with_condition (fun)": [
    "_test_sink (fun)", "_test_source (fun)", "isinstance (fun)",
    "match.condition (fun)"
  ],
  "match.test_match_mapping_pattern (fun)": [
    "_test_sink (fun)", "_test_source (fun)", "dict.__getitem__ (method)",
    "dict.__init__ (method)", "isinstance (fun)", "object.__eq__ (method)",
    "object.__ne__ (method)", "object.__new__ (method)"
  ]
}