@generated
Call dependencies
maximum_tito_depth.tito_max_consecutive (fun) -> [maximum_tito_depth.tito_one (fun) maximum_tito_depth.tito_two (fun) maximum_tito_depth.tito_zero (fun)]
maximum_tito_depth.tito_min_disjoint (fun) -> [maximum_tito_depth.tito_one (fun) maximum_tito_depth.tito_zero (fun)]
maximum_tito_depth.tito_min_disjoint_max_consecutive (fun) -> [maximum_tito_depth.tito_one (fun) maximum_tito_depth.tito_two (fun) maximum_tito_depth.tito_zero (fun)]
maximum_tito_depth.tito_obscure (fun) -> [maximum_tito_depth.C::tito (method) object::__init__ (method) object::__new__ (method)]
maximum_tito_depth.tito_one (fun) -> [maximum_tito_depth.tito_zero (fun)]
maximum_tito_depth.tito_two (fun) -> [maximum_tito_depth.tito_one (fun)]
maximum_tito_depth.tito_zero (fun) -> []
