@generated
Call dependencies
{
  "model_query_parent_decorator.TestC_1.__init__ (method)": [
    "pysa._test_sink (fun)"
  ],
  "model_query_parent_decorator.TestC_2.__init__ (method)": [
    "pysa._test_sink (fun)"
  ],
  "model_query_parent_decorator.TestC_3.__init__ (method)": [
    "pysa._test_sink (fun)"
  ],
  "model_query_parent_decorator.setup (fun)": [
    "builtins.object.__new__ (method)",
    "model_query_parent_decorator.TestC_1.__init__ (method)",
    "model_query_parent_decorator.TestC_2.__init__ (method)",
    "model_query_parent_decorator.TestC_3.__init__ (method)"
  ]
}