@generated
Call dependencies
model_query_parent_decorator.$toplevel (fun) -> []
model_query_parent_decorator.d1 (fun) -> []
model_query_parent_decorator.d2 (fun) -> []
model_query_parent_decorator.setup (fun) -> [model_query_parent_decorator.TestC_1::__init__ (method) model_query_parent_decorator.TestC_2::__init__ (method) model_query_parent_decorator.TestC_3::__init__ (method) object::__new__ (method)]
model_query_parent_decorator.TestC::$class_toplevel (method) -> []
model_query_parent_decorator.TestC_1::$class_toplevel (method) -> []
model_query_parent_decorator.TestC_1::__init__ (method) -> [_test_sink (fun)]
model_query_parent_decorator.TestC_2::$class_toplevel (method) -> []
model_query_parent_decorator.TestC_2::__init__ (method) -> [_test_sink (fun)]
model_query_parent_decorator.TestC_3::$class_toplevel (method) -> []
model_query_parent_decorator.TestC_3::__init__ (method) -> [_test_sink (fun)]
