@generated
Call dependencies
{
  "model_shaping._asdict_inner (fun)": [
    "dict.items (method)", "getattr (fun)", "isinstance (fun)",
    "list.__init__ (method)", "list.__iter__ (method)",
    "list.append (method)", "model_shaping._asdict_inner (fun)",
    "model_shaping._is_dataclass_instance (fun)",
    "model_shaping.fields (fun)", "object.__new__ (method)",
    "tuple.__init__ (method)", "type.__init__ (method)",
    "type.__new__ (method)", "typing.GenericMeta.__getitem__ (method)",
    "typing.Iterable.__iter__ (method)", "typing.Iterator.__next__ (method)",
    "typing.cast (fun)"
  ],
  "model_shaping.asdict (fun)": [ "model_shaping._asdict_inner (fun)" ],
  "model_shaping.asdict_test (fun)": [ "model_shaping.asdict (fun)" ],
  "model_shaping.obscure_test (fun)": [
    "pysa._test_source (fun)", "type.__init__ (method)",
    "type.__new__ (method)"
  ],
  "model_shaping.shape_multi_sink (fun)": [
    "pysa._rce (fun)", "pysa._sql (fun)"
  ],
  "model_shaping.shape_multi_source (fun)": [
    "int.__gt__ (method)", "int.__le__ (method)", "pysa._cookies (fun)",
    "pysa._user_controlled (fun)"
  ],
  "model_shaping.test_tito_shaping (fun)": [
    "dict.__getitem__ (method)", "model_shaping.tito_shaping (fun)",
    "pysa._test_sink (fun)", "pysa._test_source (fun)"
  ],
  "model_shaping.tito_shaping (fun)": [
    "dict.get (method)", "object.__repr__ (method)"
  ]
}