@generated
Call dependencies
{
  "model_query_global_variable.$toplevel (fun)": [
    "builtins.int.__add__ (method)", "builtins.int.__new__ (method)",
    "builtins.object.__init__ (method)",
    "model_query_global_variable.fun (fun)",
    "model_query_global_variable.returns_any (fun)", "pysa._test_sink (fun)",
    "pysa._test_source (fun)"
  ],
  "model_query_global_variable.f (fun)": [ "pysa._test_sink (fun)" ],
  "model_query_global_variable.fun (fun)": [
    "builtins.int.__add__ (method)", "builtins.int.__new__ (method)",
    "builtins.object.__init__ (method)"
  ],
  "model_query_global_variable.g (fun)": [ "builtins.list.append (method)" ],
  "model_query_global_variable.h (fun)": [ "pysa._test_sink (fun)" ],
  "model_query_global_variable.returns_any (fun)": [
    "builtins.object.__init__ (method)", "builtins.object.__new__ (method)"
  ]
}