@generated
Call dependencies
{
  "model_query_parameters_where.test1_alarm1 (fun)": [
    "pysa._test_sink (fun)"
  ],
  "model_query_parameters_where.test1_alarm2 (fun)": [
    "pysa._test_sink (fun)"
  ],
  "model_query_parameters_where.test1_alarm3 (fun)": [
    "pysa._test_sink (fun)"
  ],
  "model_query_parameters_where.test1_alarm4 (fun)": [
    "pysa._test_sink (fun)"
  ],
  "model_query_parameters_where.test1_args_kwargs (fun)": [
    "pysa._test_sink (fun)"
  ],
  "model_query_parameters_where.test1_positional_arguments (fun)": [
    "pysa._test_sink (fun)"
  ],
  "model_query_parameters_where.test2_noalarm1 (fun)": [
    "pysa._test_sink (fun)"
  ],
  "model_query_parameters_where.test2_noalarm2 (fun)": [
    "pysa._test_sink (fun)"
  ],
  "model_query_parameters_where.test3_alarm1 (fun)": [
    "pysa._test_sink (fun)"
  ],
  "model_query_parameters_where.test3_alarm2 (fun)": [
    "pysa._test_sink (fun)"
  ],
  "model_query_parameters_where.test3_noalarm1 (fun)": [
    "pysa._test_sink (fun)"
  ],
  "model_query_parameters_where.test3_noalarm2 (fun)": [
    "pysa._test_sink (fun)"
  ],
  "model_query_parameters_where.test4_alarm1 (fun)": [
    "pysa._test_sink (fun)"
  ],
  "model_query_parameters_where.test4_alarm2 (fun)": [
    "pysa._test_sink (fun)"
  ],
  "model_query_parameters_where.test4_noalarm1 (fun)": [
    "pysa._test_sink (fun)"
  ],
  "model_query_parameters_where.test4_noalarm2 (fun)": [
    "pysa._test_sink (fun)"
  ],
  "model_query_parameters_where.test6_alarm1 (fun)": [
    "pysa._test_sink (fun)"
  ],
  "model_query_parameters_where.test6_alarm2 (fun)": [
    "pysa._test_sink (fun)"
  ],
  "model_query_parameters_where.test6_noalarm1 (fun)": [
    "pysa._test_sink (fun)"
  ],
  "model_query_parameters_where.test6_noalarm2 (fun)": [
    "pysa._test_sink (fun)"
  ],
  "model_query_parameters_where.test8_alarm1 (fun)": [
    "pysa._test_sink (fun)"
  ],
  "model_query_parameters_where.test8_alarm2 (fun)": [
    "pysa._test_sink (fun)"
  ],
  "model_query_parameters_where.test8_alarm3 (fun)": [
    "pysa._test_sink (fun)"
  ],
  "model_query_parameters_where.test8_alarm4 (fun)": [
    "pysa._test_sink (fun)"
  ]
}