@generated
Call dependencies
{
  "model_shaping._asdict_inner (fun)": [
    "builtins.dict.items (method)", "builtins.getattr (fun)",
    "builtins.isinstance (fun)", "builtins.list.__iter__ (method)",
    "builtins.list.append (method)", "builtins.tuple.__iter__ (method)",
    "builtins.type.__init__ (method)", "builtins.type.__new__ (method)",
    "model_shaping._asdict_inner (fun)",
    "model_shaping._is_dataclass_instance (fun)",
    "model_shaping.fields (fun)", "typing.ItemsView.__iter__ (method)",
    "typing.Iterator.__next__ (method)", "typing.cast (fun)"
  ],
  "model_shaping.asdict (fun)": [ "model_shaping._asdict_inner (fun)" ],
  "model_shaping.asdict_test (fun)": [ "model_shaping.asdict (fun)" ],
  "model_shaping.obscure_test (fun)": [
    "builtins.type.__init__ (method)", "builtins.type.__new__ (method)",
    "pysa._test_source (fun)"
  ],
  "model_shaping.shape_multi_sink (fun)": [
    "pysa._rce (fun)", "pysa._sql (fun)"
  ],
  "model_shaping.shape_multi_source (fun)": [ "pysa._cookies (fun)" ],
  "model_shaping.test_tito_shaping (fun)": [
    "builtins.dict.__getitem__ (method)", "model_shaping.tito_shaping (fun)",
    "pysa._test_sink (fun)", "pysa._test_source (fun)"
  ],
  "model_shaping.tito_shaping (fun)": [
    "builtins.dict.get (method)", "builtins.object.__init__ (method)",
    "builtins.object.__repr__ (method)", "builtins.str.__new__ (method)"
  ]
}