@generated
Call dependencies
{
  "model_query_global_variable.$toplevel (fun)": [
    "int.__new__ (method)", "model_query_global_variable.fun (fun)",
    "model_query_global_variable.returns_any (fun)",
    "object.__init__ (method)", "pysa._test_sink (fun)",
    "pysa._test_source (fun)"
  ],
  "model_query_global_variable.f (fun)": [
    "os.environ (object)", "pysa._test_sink (fun)"
  ],
  "model_query_global_variable.fun (fun)": [
    "int.__add__ (method)", "int.__new__ (method)",
    "object.__init__ (method)"
  ],
  "model_query_global_variable.g (fun)": [ "list.append (method)" ],
  "model_query_global_variable.h (fun)": [ "pysa._test_sink (fun)" ],
  "model_query_global_variable.returns_any (fun)": [
    "object.__init__ (method)", "object.__new__ (method)"
  ]
}