@generated
Call dependencies
{
  "multiple_sources_string_operations.DatabaseSchemaEditor.string_operations (method)": [
    "multiple_sources_string_operations.user_controlled_input (fun)",
    "str.format (method)"
  ],
  "multiple_sources_string_operations.format_string_issue (fun)": [
    "multiple_sources_string_operations.user_controlled_input (fun)",
    "object.__repr__ (method)", "str.__str__ (method)"
  ],
  "multiple_sources_string_operations.format_string_issue_string_literal (fun)": [
    "multiple_sources_string_operations.user_controlled_input (fun)"
  ],
  "multiple_sources_string_operations.format_string_issue_with_multiple_triggered_user_controlled (fun)": [
    "multiple_sources_string_operations.format_string_multiple_triggered_user_controlled (fun)",
    "multiple_sources_string_operations.user_controlled_input (fun)"
  ],
  "multiple_sources_string_operations.format_string_issue_with_triggered_sql (fun)": [
    "multiple_sources_string_operations.format_string_triggered_sql (fun)"
  ],
  "multiple_sources_string_operations.format_string_issue_with_triggered_user_controlled (fun)": [
    "multiple_sources_string_operations.format_string_triggered_user_controlled (fun)",
    "multiple_sources_string_operations.user_controlled_input (fun)"
  ],
  "multiple_sources_string_operations.format_string_multiple_issues_string_literal (fun)": [
    "multiple_sources_string_operations.user_controlled_input (fun)"
  ],
  "multiple_sources_string_operations.format_string_no_issue_when_single_sink_parameter (fun)": [
    "int.__eq__ (method)", "int.__ne__ (method)",
    "multiple_sources_string_operations.user_controlled_input (fun)",
    "str.__str__ (method)"
  ],
  "multiple_sources_string_operations.format_string_triggered_sql (fun)": [
    "multiple_sources_string_operations.user_controlled_input (fun)"
  ],
  "multiple_sources_string_operations.format_string_triggered_user_controlled (fun)": [
    "str.__str__ (method)"
  ],
  "multiple_sources_string_operations.nested_stradd_and_fstring (fun)": [
    "multiple_sources_string_operations.user_controlled_input (fun)",
    "str.__add__ (method)", "str.__str__ (method)"
  ],
  "multiple_sources_string_operations.stradd_tito_triggered_user_controlled (fun)": [
    "multiple_sources_string_operations.tito (fun)",
    "multiple_sources_string_operations.user_controlled_input (fun)",
    "str.__add__ (method)"
  ],
  "multiple_sources_string_operations.stradd_triggered_user_controlled (fun)": [
    "multiple_sources_string_operations.user_controlled_input (fun)",
    "str.__add__ (method)"
  ],
  "multiple_sources_string_operations.string_operations (fun)": [
    "multiple_sources_string_operations.user_controlled_input (fun)",
    "str.__add__ (method)", "str.__mod__ (method)", "str.format (method)"
  ],
  "multiple_sources_string_operations.test_large_string_add (fun)": [
    "int.__mul__ (method)", "int.__new__ (method)",
    "object.__init__ (method)", "object.__repr__ (method)",
    "str.__add__ (method)", "str.__str__ (method)"
  ]
}