@generated
Call dependencies
multiple_sources_string_operations.$toplevel (fun) -> []
multiple_sources_string_operations.string_operations (fun) -> [multiple_sources_string_operations.user_controlled_input (fun) str::__add__ (method) str::__mod__ (method) str::__str__ (method) str::format (method)]
multiple_sources_string_operations.user_controlled_input (fun) -> []
multiple_sources_string_operations.DatabaseSchemaEditor::$class_toplevel (method) -> []
multiple_sources_string_operations.DatabaseSchemaEditor::string_operations (method) -> [multiple_sources_string_operations.user_controlled_input (fun) str::format (method)]
