@generated
Call dependencies
{
  "mutate_self.Base.bar_sink (method)": [ "_test_sink (fun)" ],
  "mutate_self.Base.foo_sink (method)": [ "_test_sink (fun)" ],
  "mutate_self.Base.isssue_mutates_foo (method)": [
    "mutate_self.Base.bar_sink (method)",
    "mutate_self.Base.foo_sink (method)",
    "mutate_self.Base.mutates_foo (method)"
  ],
  "mutate_self.Base.issue_mutates_and_returns (method)": [
    "mutate_self.Base.foo_sink (method)",
    "mutate_self.Base.mutates_foo_and_returns (method)"
  ],
  "mutate_self.Base.issue_mutates_foo_self_annotation (method)": [
    "mutate_self.Base.bar_sink (method)",
    "mutate_self.Base.foo_sink (method)",
    "mutate_self.Base.mutates_foo_self_annotation (method)"
  ],
  "mutate_self.Base.issue_mutates_foo_self_typevar (method)": [
    "mutate_self.Base.bar_sink (method)",
    "mutate_self.Base.foo_sink (method)",
    "mutate_self.Base.mutates_foo_self_typevar (method)"
  ],
  "mutate_self.Base.issue_mutates_foo_with_hop (method)": [
    "mutate_self.Base.bar_sink (method)",
    "mutate_self.Base.foo_sink (method)",
    "mutate_self.Base.mutates_foo_with_hop (method)"
  ],
  "mutate_self.Base.mutates_foo (method)": [ "_test_source (fun)" ],
  "mutate_self.Base.mutates_foo_and_returns (method)": [
    "_test_source (fun)"
  ],
  "mutate_self.Base.mutates_foo_self_annotation (method)": [
    "_test_source (fun)"
  ],
  "mutate_self.Base.mutates_foo_self_typevar (method)": [
    "_test_source (fun)"
  ],
  "mutate_self.Base.mutates_foo_with_hop (method)": [
    "mutate_self.Base.mutates_foo (method)"
  ],
  "mutate_self.free_function_mutates_self (fun)": [ "_test_source (fun)" ],
  "mutate_self.issue_free_function (fun)": [
    "mutate_self.Base.__init__ (method)",
    "mutate_self.Base.bar_sink (method)",
    "mutate_self.Base.foo_sink (method)",
    "mutate_self.free_function_mutates_self (fun)", "object.__new__ (method)"
  ],
  "mutate_self.issue_mutates_foo_and_returns_instance (fun)": [
    "mutate_self.Base.__init__ (method)",
    "mutate_self.Base.foo_sink (method)",
    "mutate_self.Base.mutates_foo_and_returns (method)",
    "object.__new__ (method)"
  ],
  "mutate_self.issue_mutates_foo_instance (fun)": [
    "mutate_self.Base.__init__ (method)",
    "mutate_self.Base.bar_sink (method)",
    "mutate_self.Base.foo_sink (method)",
    "mutate_self.Base.mutates_foo (method)", "object.__new__ (method)"
  ]
}