@generated
Call dependencies
{
  "nested_callables.access_parameter_in_inner_scope_sink (fun)": [
    "nested_callables.access_parameter_in_inner_scope_sink.inner (fun)"
  ],
  "nested_callables.access_parameter_in_inner_scope_sink.inner (fun)": [
    "pysa._test_sink (fun)"
  ],
  "nested_callables.access_parameter_in_inner_scope_tito (fun)": [
    "nested_callables.access_parameter_in_inner_scope_tito.inner (fun)"
  ],
  "nested_callables.access_variables_in_outer_scope_issue (fun)": [
    "nested_callables.access_variables_in_outer_scope_issue.inner (fun)",
    "pysa._test_source (fun)"
  ],
  "nested_callables.access_variables_in_outer_scope_issue.inner (fun)": [
    "pysa._test_sink (fun)"
  ],
  "nested_callables.access_variables_in_outer_scope_source (fun)": [
    "nested_callables.access_variables_in_outer_scope_source.inner (fun)",
    "pysa._test_source (fun)"
  ],
  "nested_callables.call_outer (fun)": [
    "nested_callables.outer (fun)", "pysa._test_source (fun)"
  ],
  "nested_callables.duplicate_function (fun)": [
    "nested_callables.foo (fun)"
  ],
  "nested_callables.duplicate_function$2 (fun)": [
    "nested_callables.foo (fun)"
  ],
  "nested_callables.foo.inner (fun)": [
    "pysa._test_sink (fun)", "pysa._test_source (fun)"
  ],
  "nested_callables.foo.inner_with_model (fun)": [
    "pysa._test_source (fun)"
  ],
  "nested_callables.nested_global_function (fun)": [
    "nested_callables.nested_global_function.g (fun)"
  ],
  "nested_callables.nested_global_function.g (fun)": [
    "builtins.str.__add__ (method)"
  ],
  "nested_callables.outer (fun)": [ "nested_callables.outer.inner (fun)" ],
  "nested_callables.outer.inner (fun)": [ "pysa._test_sink (fun)" ],
  "nested_callables.outer_calling_other_function (fun)": [
    "nested_callables.outer_calling_other_function.inner_calling_other_function (fun)"
  ],
  "nested_callables.outer_calling_other_function.inner_calling_other_function (fun)": [
    "nested_callables.some_sink (fun)"
  ],
  "nested_callables.parameter_function (fun)": [
    "nested_callables.parameter_function.add (fun)"
  ],
  "nested_callables.parameter_function.add (fun)": [
    "builtins.str.__add__ (method)"
  ],
  "nested_callables.some_sink (fun)": [ "pysa._test_sink (fun)" ],
  "nested_callables.test_access_parameter_in_inner_scope_sink (fun)": [
    "nested_callables.access_parameter_in_inner_scope_sink (fun)",
    "pysa._test_source (fun)"
  ],
  "nested_callables.test_access_parameter_in_inner_scope_tito (fun)": [
    "nested_callables.access_parameter_in_inner_scope_tito (fun)",
    "pysa._test_sink (fun)", "pysa._test_source (fun)"
  ],
  "nested_callables.test_access_variables_in_outer_scope_source (fun)": [
    "nested_callables.access_variables_in_outer_scope_source (fun)",
    "pysa._test_sink (fun)"
  ],
  "nested_callables.test_mutation_of_class (fun)": [
    "builtins.object.__init__ (method)", "builtins.object.__new__ (method)",
    "nested_callables.test_mutation_of_class.set_a (fun)",
    "pysa._test_sink (fun)"
  ],
  "nested_callables.test_mutation_of_class.set_a (fun)": [
    "pysa._test_source (fun)"
  ]
}