@generated
Call dependencies
obscure_tito.test_obscure_return (fun) -> [_test_source (fun) object::__init__ (method) object::__new__ (method) obscure_tito.C::update (override)]
obscure_tito.test_obscure_sink (fun) -> [object::__init__ (method) object::__new__ (method) obscure_tito.C::taint_parameter (override)]
obscure_tito.test_obscure_tito (fun) -> [_test_source (fun) object::__init__ (method) object::__new__ (method) obscure_tito.C::update (override)]
