@generated
Call dependencies
{
  "parametric_models.f_and_g_to_test (fun)": [
    "float.__gt__ (method)", "float.__le__ (method)",
    "parametric_models.f (fun)", "parametric_models.g (fun)",
    "parametric_models.sink (fun)", "random.random (fun)"
  ],
  "parametric_models.inferred_sink (fun)": [
    "float.__gt__ (method)", "float.__le__ (method)",
    "parametric_models.sink_subkind_a (fun)",
    "parametric_models.sink_subkind_b (fun)", "random.random (fun)"
  ],
  "parametric_models.test_to_subkind_sink (fun)": [
    "parametric_models.inferred_sink (fun)", "pysa._test_source (fun)"
  ]
}