@generated
Call dependencies
parametric_models.$toplevel (fun) -> []
parametric_models.f_and_g_to_test (fun) -> [int::__gt__ (method) int::__le__ (method) parametric_models.f (fun) parametric_models.g (fun) parametric_models.sink (fun)]
parametric_models.inferred_sink (fun) -> [int::__gt__ (method) int::__le__ (method) parametric_models.sink_subkind_a (fun) parametric_models.sink_subkind_b (fun)]
parametric_models.test_to_subkind_sink (fun) -> [_test_source (fun) parametric_models.inferred_sink (fun)]
