@generated
Call dependencies
{
  "partial.MyClass.sink_on_foo (method)": [ "pysa._test_sink (fun)" ],
  "partial.NestedDefineConstructor.__init__@decorated (method)": [
    "object.__new__ (method)",
    "partial.NestedDefineDecorator.__init__ (method)[formal(func, position=1)=partial.NestedDefineConstructor.__init__ (method)]"
  ],
  "partial.NestedDefineDecorator.__call__ (method)": [
    "typing.MutableMapping.pop (method)"
  ],
  "partial.NestedDefineDecorator.__get__.wrapper (fun)": [
    "dict.__setitem__ (method)",
    "partial.NestedDefineDecorator.__call__ (method)"
  ],
  "partial.PartialConstructor.__init__@decorated (method)": [
    "object.__new__ (method)",
    "partial.PartialDecorator.__init__ (method)[formal(func, position=1)=functools.partial.__call__ (method)]",
    "partial.PartialDecorator.__init__ (method)[formal(func, position=1)=partial.PartialConstructor.__init__ (method)]"
  ],
  "partial.PartialDecorator.__call__ (method)": [
    "typing.MutableMapping.pop (method)"
  ],
  "partial.PartialDecorator.__get__ (method)": [
    "functools.partial.__init__ (method)", "object.__new__ (method)",
    "partial.PartialDecorator.__call__ (method)"
  ],
  "partial.a_flows_to_sink (fun)": [ "pysa._test_sink (fun)" ],
  "partial.dunder_call_partial_constructor (fun)": [
    "functools.partial.__call__ (method)", "object.__new__ (method)"
  ],
  "partial.multiprocessing_bound_method_issue (fun)": [
    "multiprocessing.context.Process.__init__ (method)",
    "object.__new__ (method)", "partial.MyClass.sink_on_foo (method)",
    "pysa._test_source (fun)"
  ],
  "partial.multiprocessing_bound_method_sink (fun)": [
    "multiprocessing.context.Process.__init__ (method)",
    "object.__new__ (method)", "partial.MyClass.sink_on_foo (method)"
  ],
  "partial.multiprocessing_infer_sinks (fun)": [
    "multiprocessing.context.Process.__init__ (method)",
    "object.__new__ (method)", "partial.a_flows_to_sink (fun)"
  ],
  "partial.multiprocessing_nested_sink (fun)": [
    "dict.__getitem__ (method)",
    "multiprocessing.context.Process.__init__ (method)",
    "object.__new__ (method)", "partial.MyClass.__init__ (method)",
    "partial.sink_on_foo (fun)"
  ],
  "partial.multiprocessing_no_sink (fun)": [
    "dict.__getitem__ (method)",
    "multiprocessing.context.Process.__init__ (method)",
    "object.__new__ (method)", "partial.MyClass.__init__ (method)",
    "partial.sink_on_foo (fun)"
  ],
  "partial.multiprocessing_not_tainted (fun)": [
    "multiprocessing.context.Process.__init__ (method)",
    "object.__new__ (method)", "partial.a_flows_to_sink (fun)",
    "pysa._test_source (fun)"
  ],
  "partial.multiprocessing_shim_fail (fun)": [
    "multiprocessing.context.Process.__init__ (method)",
    "object.__new__ (method)", "partial.a_flows_to_sink (fun)",
    "pysa._test_source (fun)"
  ],
  "partial.multiprocessing_tainted (fun)": [
    "multiprocessing.context.Process.__init__ (method)",
    "object.__new__ (method)", "partial.a_flows_to_sink (fun)",
    "pysa._test_source (fun)"
  ],
  "partial.multiprocessing_tainted_access_path (fun)": [
    "multiprocessing.context.Process.__init__ (method)",
    "object.__new__ (method)", "partial.MyClass.__init__ (method)",
    "partial.sink_on_foo (fun)", "pysa._test_source (fun)"
  ],
  "partial.partial_application_bound_method_sink (fun)": [
    "functools.partial.__init__ (method)", "object.__new__ (method)",
    "partial.MyClass.sink_on_foo (method)"
  ],
  "partial.partial_application_bound_method_tito (fun)": [
    "functools.partial.__init__ (method)", "object.__new__ (method)",
    "partial.MyClass.set_foo (method)", "pysa._test_source (fun)"
  ],
  "partial.partial_application_with_benign (fun)": [
    "functools.partial.__init__ (method)", "object.__new__ (method)",
    "partial.a_flows_to_sink (fun)"
  ],
  "partial.partial_application_with_named_a (fun)": [
    "functools.partial.__init__ (method)", "object.__new__ (method)",
    "partial.a_flows_to_sink (fun)", "pysa._test_source (fun)"
  ],
  "partial.partial_application_with_named_b (fun)": [
    "functools.partial.__init__ (method)", "object.__new__ (method)",
    "partial.a_flows_to_sink (fun)", "pysa._test_source (fun)"
  ],
  "partial.partial_application_with_tainted (fun)": [
    "functools.partial.__init__ (method)", "object.__new__ (method)",
    "partial.a_flows_to_sink (fun)", "pysa._test_source (fun)"
  ],
  "partial.sink_on_foo (fun)": [ "pysa._test_sink (fun)" ]
}