@generated
Call dependencies
{
  "recognized_callable_targets.callable_target (fun)": [
    "pysa._test_sink (fun)"
  ],
  "recognized_callable_targets.callable_target@decorated (fun)": [
    "pysa.to_callable_target (fun)",
    "recognized_callable_targets.callable_target (fun)"
  ],
  "recognized_callable_targets.test_callable_target (fun)": [
    "pysa._test_source (fun)",
    "recognized_callable_targets.callable_target (fun)"
  ]
}