@generated
Call dependencies
{
  "sanitize_parametric.partial_issue_sanitize (fun)": [
    "sanitize_parametric.partial_issue_sinks (fun)",
    "sanitize_parametric.partial_issue_sources (fun)"
  ],
  "sanitize_parametric.partial_issue_sinks (fun)": [
    "float.__gt__ (method)", "float.__le__ (method)", "random.random (fun)",
    "sanitize_parametric.a_sink_x (fun)",
    "sanitize_parametric.a_sink_y (fun)",
    "sanitize_parametric.sanitize_a_source_tito (fun)"
  ],
  "sanitize_parametric.partial_issue_sources (fun)": [
    "float.__gt__ (method)", "float.__le__ (method)", "random.random (fun)",
    "sanitize_parametric.a_source_x (fun)",
    "sanitize_parametric.a_source_y (fun)",
    "sanitize_parametric.sanitize_a_sink_tito (fun)"
  ]
}