@generated
Call dependencies
skip_analysis.$toplevel (fun) -> []
skip_analysis.no_issue_due_to_skip (fun) -> [_test_sink (fun) _test_source (fun) object::__init__ (method) object::__new__ (method) skip_analysis.SkipMe::taint_here (method) skip_analysis.SkipMe::tito_here (method)]
skip_analysis.SkipMe::$class_toplevel (method) -> []
skip_analysis.SkipMe::taint_here (method) -> [_test_sink (fun)]
skip_analysis.SkipMe::tito_here (method) -> []
