@generated
Call dependencies
string_conversion.$toplevel (fun) -> []
string_conversion.ReprIsTainted::$class_toplevel (method) -> []
string_conversion.ReprIsTainted::__repr__ (method) -> [dict::__getitem__ (method)]
string_conversion.StrIsTainted::$class_toplevel (method) -> []
string_conversion.StrIsTainted::__str__ (method) -> [dict::__getitem__ (method)]
string_conversion.repr_is_tainted (fun) -> [eval (fun) object::__init__ (method) object::__new__ (method) string_conversion.ReprIsTainted::__repr__ (method)]
string_conversion.str_falls_back_to_repr (fun) -> [eval (fun) object::__init__ (method) object::__new__ (method) string_conversion.ReprIsTainted::__repr__ (method)]
string_conversion.str_is_tainted (fun) -> [eval (fun) object::__init__ (method) object::__new__ (method) string_conversion.StrIsTainted::__str__ (method)]
