@generated
Call dependencies
taint_broadening.issue_collapse (fun) -> [_test_sink (fun) _test_source (fun)]
taint_broadening.simplify_collapse_source (fun) -> [_test_source (fun) dict::__setitem__ (method)]
taint_broadening.sink_a (fun) -> [_test_sink (fun)]
taint_broadening.tito (fun) -> []
taint_broadening.tito_collapse_issue (fun) -> [_test_sink (fun) _test_source (fun) taint_broadening.tito (fun)]
taint_broadening.tito_collapse_sink (fun) -> [_test_sink (fun) taint_broadening.tito (fun)]
taint_broadening.tito_collapse_source (fun) -> [_test_source (fun) taint_broadening.tito (fun)]
taint_broadening.widen_collapse_sink (fun) -> [_test_sink (fun)]
taint_broadening.widen_collapse_source (fun) -> [_test_source (fun) dict::__getitem__ (method)]
