@generated
Call dependencies
typed_dict.$toplevel (fun) -> []
typed_dict.test_sanitize_field (fun) -> [TypedDictionary::__getitem__ (method) _test_sink (fun) _test_source (fun)]
typed_dict.test_typed_dict_constructor (fun) -> [TypedDictionary::__getitem__ (method) _test_sink (fun) _test_source (fun) object::__new__ (method) str::__getitem__ (method) typed_dict.SimpleTypedDict::__init__ (method) typing.Mapping::keys (method)]
typed_dict.test_typed_dict_setitem (fun) -> [TypedDictionary::__getitem__ (method) TypedDictionary::__setitem__ (method) _test_sink (fun) _test_source (fun)]
typed_dict.NestedTypedDict::$class_toplevel (method) -> []
typed_dict.SanitizedFieldTypedDict::$class_toplevel (method) -> []
typed_dict.SimpleTypedDict::$class_toplevel (method) -> []
