@generated
Call dependencies
typed_dict.$toplevel (fun) -> []
typed_dict.test1 (fun) -> [TypedDictionary::__getitem__ (method) _test_sink (fun) _test_source (fun)]
typed_dict.test2 (fun) -> [TypedDictionary::__getitem__ (method) _test_sink (fun) _test_source (fun)]
typed_dict.test3 (fun) -> [TypedDictionary::__getitem__ (method) _test_sink (fun) _test_source (fun)]
typed_dict.Bar::$class_toplevel (method) -> []
typed_dict.Foo::$class_toplevel (method) -> []
