@generated
Call dependencies
{
  "typed_dict.test_sanitize_field (fun)": [
    "pysa._test_sink (fun)", "pysa._test_source (fun)"
  ],
  "typed_dict.test_typed_dict_constructor (fun)": [
    "_typeshed._type_checker_internals.TypedDictFallback.keys (method)",
    "pysa._test_sink (fun)", "pysa._test_source (fun)"
  ],
  "typed_dict.test_typed_dict_setitem (fun)": [
    "pysa._test_sink (fun)", "pysa._test_source (fun)"
  ]
}