@generated
Call dependencies
{
  "typed_dict.test_sanitize_field (fun)": [
    "TypedDictionary.__getitem__ (method)", "pysa._test_sink (fun)",
    "pysa._test_source (fun)"
  ],
  "typed_dict.test_typed_dict_constructor (fun)": [
    "TypedDictionary.__getitem__ (method)", "object.__new__ (method)",
    "pysa._test_sink (fun)", "pysa._test_source (fun)",
    "typed_dict.SimpleTypedDict.__init__ (method)",
    "typing.Mapping.keys (method)"
  ],
  "typed_dict.test_typed_dict_setitem (fun)": [
    "TypedDictionary.__getitem__ (method)",
    "TypedDictionary.__setitem__ (method)", "pysa._test_sink (fun)",
    "pysa._test_source (fun)"
  ]
}