@generated
Call dependencies
attributes.UseViaDict::__init__ (method) -> []
attributes.test_attribute (fun) -> []
attributes.test_attribute_via_dunder_dict (fun) -> [__test_sink (fun) __test_source (fun) attributes.UseViaDict::__init__ (method) object::__new__ (method)]
attributes.test_getattr_backwards (fun) -> [__test_sink (fun) getattr (fun)]
attributes.test_getattr_backwards_default (fun) -> [__test_sink (fun) getattr (fun)]
attributes.test_getattr_default (fun) -> [__test_source (fun) getattr (fun)]
attributes.test_getattr_forward (fun) -> [getattr (fun)]
attributes.test_via_non_optional (fun) -> []
attributes.test_via_optional (fun) -> []
