@generated
Call dependencies
attributes.test_attribute (fun) -> []
attributes.test_getattr_backwards (fun) -> [__test_sink (fun) getattr (fun)]
attributes.test_getattr_backwards_default (fun) -> [__test_sink (fun) getattr (fun)]
attributes.test_getattr_default (fun) -> [__test_source (fun) getattr (fun)]
attributes.test_getattr_forward (fun) -> [getattr (fun)]
attributes.test_via_non_optional (fun) -> []
attributes.test_via_optional (fun) -> []
