@generated
Call dependencies
constructors.SomeAPI::__init__ (method) -> []
constructors.SomeAPI::async_get_authenticated_user (method) -> [eval (fun)]
constructors.SomeAPI::from_default_keys (method) -> [constructors.SomeAPI::__init__ (method)]
constructors.SourceInConstructor::__init__ (method) -> [__test_source (fun)]
constructors.test_construction (fun) -> [constructors.SomeAPI::async_get_authenticated_user (method) constructors.SomeAPI::from_default_keys (method)]
constructors.test_source_in_constructor (fun) -> [__test_sink (fun) constructors.SourceInConstructor::__init__ (method)]
