@generated
Call dependencies
sanitize.return_taint_sanitize (fun) -> []
sanitize.sanitize_a_and_b_source (fun) -> [int::__gt__ (method) int::__le__ (method) sanitize.a_source (fun) sanitize.b_source (fun)]
sanitize.sanitize_sinks (fun) -> [__test_sink (fun) sanitize.source_with_tito (fun)]
sanitize.sanitize_sources (fun) -> [__test_sink (fun) sanitize.source_with_tito (fun)]
sanitize.sanitize_test_a_source (fun) -> [int::__gt__ (method) int::__le__ (method) sanitize.a_source (fun) sanitize.b_source (fun)]
sanitize.sanitize_test_b_source (fun) -> [int::__gt__ (method) int::__le__ (method) sanitize.a_source (fun) sanitize.b_source (fun)]
sanitize.sanitize_tito (fun) -> [__test_sink (fun) sanitize.source_with_tito (fun)]
sanitize.source_with_tito (fun) -> []
sanitize.test1 (fun) -> [__test_source (fun) object::__init__ (method) object::__new__ (method) sanitize.test2 (fun) sanitize.test3 (fun)]
sanitize.test2 (fun) -> [__test_sink (fun) sanitize.return_taint_sanitize (fun)]
sanitize.test3 (fun) -> [__test_sink (fun) sanitize.return_taint_sanitize (fun)]
