@generated
Call dependencies
strings.bad_1 (fun) -> [__test_sink (fun) __test_source (fun) strings.concatenate_lhs (fun)]
strings.bad_2 (fun) -> [__test_sink (fun) __test_source (fun) strings.concatenate_rhs (fun)]
strings.concatenate_lhs (fun) -> [str::__add__ (method)]
strings.concatenate_rhs (fun) -> [str::__add__ (method)]
strings.either (fun) -> [__test_sink (fun) __test_source (fun) strings.concatenate_lhs (fun) strings.concatenate_rhs (fun)]
strings.maybe_lhs (fun) -> [__test_sink (fun) __test_source (fun) strings.concatenate_lhs (fun)]
strings.maybe_rhs (fun) -> [__test_sink (fun) __test_source (fun) strings.concatenate_rhs (fun)]
