@generated
Call dependencies
taint_in_taint_out.Data::__init__ (method) -> []
taint_in_taint_out.Recursive::__init__ (method) -> [object::__new__ (method) slice::__init__ (method) taint_in_taint_out.get_related (fun)]
taint_in_taint_out.adds_tito (fun) -> []
taint_in_taint_out.get_data (fun) -> []
taint_in_taint_out.get_related (fun) -> [object::__new__ (method) taint_in_taint_out.Recursive::__init__ (method)]
taint_in_taint_out.product_data (fun) -> [taint_in_taint_out.get_data (fun) taint_in_taint_out.product_data (fun)]
taint_in_taint_out.product_data_wrapper (fun) -> [taint_in_taint_out.product_data (fun)]
taint_in_taint_out.tito (fun) -> [__test_source (fun) taint_in_taint_out.product_data_wrapper (fun)]
taint_in_taint_out.via_getattr (fun) -> [getattr (fun)]
