@generated
Call dependencies
taint_in_taint_out.Data::__init__ (method) -> []
taint_in_taint_out.get_data (fun) -> []
taint_in_taint_out.product_data (fun) -> [taint_in_taint_out.get_data (fun) taint_in_taint_out.product_data (fun)]
taint_in_taint_out.product_data_wrapper (fun) -> [taint_in_taint_out.product_data (fun)]
taint_in_taint_out.tito (fun) -> [__test_source (fun) taint_in_taint_out.product_data_wrapper (fun)]
taint_in_taint_out.via_getattr (fun) -> [getattr (fun)]
