language: python
python:
  - "3.6"

dist: xenial

jobs:
  include:
    - stage: "Build, run tests and linters"
      name: "Lint: Pyre"
      install: scripts/travis_install_lint_dependencies.sh
      script: scripts/travis_pyre_on_pyre.sh
    - name: "Lint: Black"
      install: scripts/travis_install_lint_dependencies.sh
      script: black --check --diff .
    - name: "Build and run tests"
      install: scripts/travis_install_build_dependencies.sh
      script: ./scripts/setup.sh --local
    - name: "Build and run tests for sapp"
      install: pip install -r tools/sapp/requirements.txt
      script: cd tools/sapp && python3 setup.py test
