# Copyright (c) 2016-present, Facebook, Inc.
#
# This source code is licensed under the MIT license found in the
# LICENSE file in the root directory of this source tree.

FLAGS = -use-ocamlfind -no-links -no-hygiene -cflags="-warn-error +a"
INCLUDES = . parser analysis ast test service language_server command command/server %VERSION%
BUILD = ocamlbuild $(FLAGS) $(addprefix -I , $(INCLUDES))

TEST_FLAGS = -runner sequential
TESTS = $(foreach include, $(INCLUDES), $(patsubst %.ml, %.native, $(wildcard $(include)/test/*Test.ml)))

.PHONY: all
all: hack_parallel development_tags
	$(BUILD) -build-dir _build/all main.native

.PHONY: byte
byte:
	$(BUILD) -build-dir _build/byte main.byte


RUN_TESTS = $(TESTS:%=_build/test/%)

.PHONY: $(RUN_TESTS)
$(RUN_TESTS):
	@$@ $(TEST_FLAGS)

.PHONY: test
test: hack_parallel development_tags
	$(BUILD) -pkg oUnit -build-dir _build/test $(TESTS)
	@$(MAKE) --keep-going $(RUN_TESTS)

.PHONY: release
release: hack_parallel release_tags
	$(BUILD) -build-dir _build/all main.native

.PHONY: clean
clean:
	$(BUILD) -clean

.PHONY: hack_parallel
hack_parallel:
	@if [ ! -d hack_parallel/_build ]; then echo 'Hack_parallel is not installed...'; make -C hack_parallel; make install -C hack_parallel; fi
	@mkdir -p _build/hack_parallel/heap
	@mkdir -p _build/hack_parallel/utils
	@mkdir -p _build/hack_parallel/third-party/lz4
	@cp hack_parallel/_build/hack_parallel/heap/hh_shared.o _build/hack_parallel/heap/hh_shared.o
	@cp hack_parallel/_build/hack_parallel/utils/files.o _build/hack_parallel/utils/files.o
	@cp hack_parallel/_build/hack_parallel/utils/handle_stubs.o _build/hack_parallel/utils/handle_stubs.o
	@cp hack_parallel/_build/hack_parallel/utils/nproc.o _build/hack_parallel/utils/nproc.o
	@cp hack_parallel/_build/hack_parallel/utils/realpath.o _build/hack_parallel/utils/realpath.o
	@cp hack_parallel/_build/hack_parallel/utils/sysinfo.o _build/hack_parallel/utils/sysinfo.o
	@cp hack_parallel/_build/hack_parallel/utils/priorities.o _build/hack_parallel/utils/priorities.o
	@cp hack_parallel/_build/hack_parallel/third-party/lz4/lz4.o _build/hack_parallel/third-party/lz4/lz4.o
	@cp hack_parallel/_build/hack_parallel/third-party/lz4/lz4frame.o _build/hack_parallel/third-party/lz4/lz4frame.o
	@cp hack_parallel/_build/hack_parallel/third-party/lz4/lz4hc.o _build/hack_parallel/third-party/lz4/lz4hc.o
	@cp hack_parallel/_build/hack_parallel/third-party/lz4/xxhash.o _build/hack_parallel/third-party/lz4/xxhash.o
	@mkdir -p _build/all
	@cp -r _build/hack_parallel _build/all/
	@mkdir -p _build/test
	@cp -r _build/hack_parallel _build/test/

.PHONY: development_tags
development_tags:
	@cp _tags.development _tags

.PHONY: release_tags
release_tags:
	@cp _tags.release _tags

.PHONY: remove_hack_parallel
remove_hack_parallel:
	@make -C hack_parallel clean && make -C hack_parallel remove
