# Copyright (c) Meta Platforms, Inc. and affiliates.
#
# This source code is licensed under the MIT license found in the
# LICENSE file in the root directory of this source tree.

def py_parse_module_print_ast(input_code: str) -> tuple[str, str]: ...
def py_parse_module_print_ast_and_pretty_print(input_code: str) -> tuple[str, str]: ...
def py_parse_module_print_ast_pretty_print_only(input_code: str) -> tuple[str, str]: ...
def py_parse_module_print_ast_pretty_and_errors(
    input_code: str,
) -> tuple[str, str, str]: ...
def py_parse_module(input_code: str) -> None: ...
