from typing import Any

def force_text(s: str, encoding: str=..., strings_only: bool=..., errors: str=...) -> str: ...

def force_str(s: str, encoding: str=..., strings_only: bool=..., errors: str=...) -> str: ...

def force_bytes(s: str, encoding: str=..., strings_only: bool=..., errors: str=...) -> bytes: ...

def smart_text(s: str, encoding: str=..., strings_only: bool=..., errors: str=...) -> Any: ...

def smart_str(s: str, encoding: str=..., strings_only: bool=..., errors: str=...) -> Any: ...

def smart_bytes(s: bytes, encoding: str=..., strings_only: bool=..., errors: str=...) -> Any: ...

def iri_to_uri(iri: str) -> str: ...
