@generated
Call dependencies
attach_features.attach_without_tito (fun) -> []
attach_features.inferred_is_propagated (fun) -> [attach_features.source_with_inferred (fun)]
attach_features.inferred_sink (fun) -> [__test_sink (fun)]
attach_features.no_tito (fun) -> [attach_features.attach_without_tito (fun)]
attach_features.sink_is_propagated (fun) -> [attach_features.inferred_sink (fun)]
attach_features.source (fun) -> []
attach_features.source_with_inferred (fun) -> [attach_features.source (fun)]
attach_features.taint_in_taint_out (fun) -> []
attach_features.tito_and_sink (fun) -> [__test_sink (fun)]
attach_features.tito_is_propagated (fun) -> [attach_features.taint_in_taint_out (fun)]
