@generated
Call dependencies
model_simplification._asdict_inner (fun) -> [dict::items (method) getattr (fun) isinstance (fun) list::append (method) model_simplification._asdict_inner (fun) model_simplification._is_dataclass_instance (fun) model_simplification.fields (fun) typing.Iterable::__iter__ (method) typing.Iterator::__next__ (method)]
model_simplification.asdict (fun) -> [model_simplification._asdict_inner (fun)]
model_simplification.asdict_test (fun) -> [model_simplification.asdict (fun)]
model_simplification.obscure_test (fun) -> [__test_source (fun)]
