Call dependencies
test_taint_in_taint_out.Data::__init__ (method) -> []
test_taint_in_taint_out.get_data (fun) -> []
test_taint_in_taint_out.product_data (fun) -> [test_taint_in_taint_out.get_data (fun) test_taint_in_taint_out.product_data (fun)]
test_taint_in_taint_out.product_data_wrapper (fun) -> [test_taint_in_taint_out.product_data (fun)]
test_taint_in_taint_out.test_tito (fun) -> [__testSource (fun) test_taint_in_taint_out.product_data_wrapper (fun)]
