#!/bin/bash

export DOCUSAURUS_BASE_URL="$1"
export INTERNAL_STATIC_DOCS=1
yarn install

../facebook/wasm.sh
cp ../pyrefly_wasm/target/pyrefly_wasm.js src/try-pyre2/pyrefly_wasm.js
cp ../pyrefly_wasm/target/pyrefly_wasm_bg.wasm src/try-pyre2/pyrefly_wasm_bg.wasm

export USE_SIMPLE_CSS_MINIFIER=true
yarn build
