(** Copyright 2016-present Facebook. All rights reserved. **)

open Expression

module Metadata : sig
  type t = {
    autogenerated: bool;
    debug: bool;
    declare: bool;
    ignore_lines: (int * int list) list;
    strict: bool;
    version: int;
  }
  [@@deriving compare, eq, show]

  val create
    :  ?autogenerated: bool
    -> ?debug: bool
    -> ?declare: bool
    -> ?ignore_lines: (int * int list) list
    -> ?strict: bool
    -> ?version: int
    -> unit
    -> t

  val parse: string list -> t
end

type t = {
  docstring: string option;
  metadata: Metadata.t;
  path: string;
  qualifier: Expression.t Access.t;
  statements: Statement.t list;
}
[@@deriving compare, eq, show]


val create
  :  ?docstring: string option
  -> ?metadata: Metadata.t
  -> ?path: string
  -> ?qualifier: Expression.t Access.t
  -> Statement.t list
  -> t


val ignore_lines: t -> (int * int list) list

val qualifier: path:string -> Expression.t Access.t
