from typing import Any


# TODO(T22838703): currently this is just shutting up pyre. Properly typing
# this will be low hanging fruit later on.


class Form:
    _errors: Any = ...
    cleaned_data: Any = ...
    data: Any = ...
    errors: Any = ...
    fields: Any = ...
    profile: Any = ...
    user: Any = ...
    user_data: Any = ...

    def is_valid(self) -> bool:
        ...

    def as_table(self) -> str:
        ...

    async def async_is_valid(self) -> bool:
        """ Custom patch from https://fburl.com/4avw1ckd."""
        ...


class ModelForm(Form):
    ...


class ValidationError(Exception):
    ...
