# Copyright (c) Facebook, Inc. and its affiliates.
#
# This source code is licensed under the MIT license found in the
# LICENSE file in the root directory of this source tree.

# pyre-unsafe

from typing import Any, Dict, List, Optional, Tuple, Type, TypeVar, Iterable, Union

from django.db.models.base import Model as Model
from django.db.models.query import QuerySet

class BaseManager:
    creation_counter: int = ...
    auto_created: bool = ...
    use_in_migrations: bool = ...
    name: str = ...
    model: Model = ...
    db: str
    _db: Optional[str]
    def __init__(self) -> None: ...
    def deconstruct(self) -> Tuple[bool, str, None, Tuple, Dict[str, int]]: ...
    def check(self, **kwargs: Any) -> List[Any]: ...
    @classmethod
    def from_queryset(
        cls, queryset_class: Type[QuerySet], class_name: Optional[str] = ...
    ) -> Any: ...
    @classmethod
    def _get_queryset_methods(cls, queryset_class: type) -> Dict[str, Any]: ...
    def contribute_to_class(self, model: Model, name: str) -> None: ...
    def db_manager(
        self: BaseManager,
        using: Optional[str] = ...,
        hints: Optional[Dict[str, Model]] = ...,
    ) -> BaseManager: ...
    def get_queryset(self) -> QuerySet: ...

class Manager(BaseManager): ...

class RelatedManager(Manager):
    related_val: Tuple[int, ...]
    def add(self, *objs: Any, bulk: bool = ...) -> None: ...
    def remove(self, *objs: Any, bulk: bool = ...) -> None: ...
    def set(self, objs: Any, *, bulk: bool = ..., clear: bool = ...) -> None: ...
    def clear(self) -> None: ...

class ManagerDescriptor:
    manager: Manager = ...
    def __init__(self, manager: Manager) -> None: ...
    def __get__(self, instance: Optional[Model], cls: Model = ...) -> Manager: ...

class EmptyManager(Manager):
    def __init__(self, model: Model) -> None: ...
