# Copyright (c) Facebook, Inc. and its affiliates.
#
# This source code is licensed under the MIT license found in the
# LICENSE file in the root directory of this source tree.

from typing import Any, Collection, Generic, Sized, Reversible, Optional

from django.db.models.manager import Manager as Manager
from django.db.models.base import Model as Model
from django.db.models.sql.query import Query as Query

def __getattr__(name: str) -> Any: ...

class QuerySet:
    model: Model = ...
    def __init__(
        self,
        model: Model = ...,
        query: Query = ...,
        using: Any = ...,
        hints: Any = ...,
    ) -> None: ...
    @property
    def query(self) -> Query: ...
    @query.setter
    def query(self, value: Query): ...
    def as_manager(cls) -> Manager: ...
    def __deepcopy__(self, memo: Any): ...
    def __len__(self): ...
    def __iter__(self) -> Any: ...
    def __bool__(self): ...
    def __getitem__(self, k: Any): ...
    def __class_getitem__(cls, *args: Any, **kwargs: Any): ...
    def __and__(self, other: Any): ...
    def __or__(self, other: Any): ...
    def iterator(self, chunk_size: int = ...): ...
    def aggregate(self, *args: Any, **kwargs: Any): ...
    def count(self): ...
    def get(self, *args: Any, **kwargs: Any): ...
    def create(self, **kwargs: Any): ...
    def bulk_create(
        self, objs: Any, batch_size: Any = ..., ignore_conflicts: bool = ...
    ): ...
    def bulk_update(self, objs: Any, fields: Any, batch_size: Any = ...) -> None: ...
    def get_or_create(self, defaults: Any = ..., **kwargs: Any): ...
    def update_or_create(self, defaults: Any = ..., **kwargs: Any): ...
    def earliest(self, *fields: Any): ...
    def latest(self, *fields: Any): ...
    def first(self): ...
    def last(self): ...
    def in_bulk(self, id_list: Any = ..., *, field_name: str = ...): ...
    def delete(self): ...
    def update(self, **kwargs: Any): ...
    def exists(self): ...
    def explain(self, *, format: Any = ..., **options: Any): ...
    def raw(
        self,
        raw_query: str,
        params: Any = ...,
        translations: Any = ...,
        using: Optional[str] = ...,
    ) -> Any: ...
    def values(self, *fields: Any, **expressions: Any): ...
    def values_list(self, *fields: Any, flat: bool = ..., named: bool = ...): ...
    def dates(self, field_name: Any, kind: Any, order: str = ...): ...
    def datetimes(
        self,
        field_name: Any,
        kind: Any,
        order: str = ...,
        tzinfo: Any = ...,
        is_dst: Any = ...,
    ): ...
    def none(self): ...
    def all(self): ...
    def filter(self, *args: Any, **kwargs: Any): ...
    def exclude(self, *args: Any, **kwargs: Any): ...
    def complex_filter(self, filter_obj: Any): ...
    def union(self, *other_qs: Any, all: bool = ...): ...
    def intersection(self, *other_qs: Any): ...
    def difference(self, *other_qs: Any): ...
    def select_for_update(
        self,
        nowait: bool = ...,
        skip_locked: bool = ...,
        of: Any = ...,
        no_key: bool = ...,
    ): ...
    def select_related(self, *fields: Any): ...
    def prefetch_related(self, *lookups: Any): ...
    def annotate(self, *args: Any, **kwargs: Any): ...
    def alias(self, *args: Any, **kwargs: Any): ...
    def order_by(self, *field_names: Any): ...
    def distinct(self, *field_names: Any): ...
    def extra(
        self,
        select: Any = ...,
        where: Any = ...,
        params: Any = ...,
        tables: Any = ...,
        order_by: Any = ...,
        select_params: Any = ...,
    ): ...
    def reverse(self): ...
    def defer(self, *fields: Any): ...
    def only(self, *fields: Any): ...
    def using(self, alias: Any): ...
    @property
    def ordered(self): ...
    @property
    def db(self): ...
    def resolve_expression(self, *args: Any, **kwargs: Any): ...
