name: lint

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  black:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2

      - name: Install black
        run: pip install black==21.4b2

      - name: Run black
        run: black --diff .

  usort:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2

      - name: Install black
        run: pip install usort==0.6.4

      - name: Run black
        run: usort diff .
