name: lint

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  pre-commit-lints:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install pre-commit
        run: pip install -r requirements-dev.txt

      - name: Run pre-commit on all files
        run: pre-commit run --all-files
