name: lint

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  black:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2

      - name: Install black
        run: pip install black==21.4b2

      - name: Run black
        run: black --check --diff .

  usort:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2

      - name: Install usort
        run: pip install usort==0.6.4

      - name: Run usort
        run: usort diff . && usort check .

  flake8:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2

      - name: Install flake8
        run: pip install flake8

      - name: Run flake8
        run: flake8
